[package]
name = "poly"
version = "1.0.0"
license = "MIT"

[profiles.lnako-dev]
runtime = "lnako"
os = "macos"
cpu = "aarch64"
abi = "gnu"

[profiles.cnako-dev]
runtime = "cnako"
os = "linux"
cpu = "x86_64"
abi = "none"

[profiles.common]
runtime = "any"
os = "linux"
cpu = "x86_64"
abi = "gnu"

[[exports]]
name = "poly"
path = "src/index.nako3"
