const shared = @import("shared.zig");
const builtins = @import("builtins.zig");

const std = shared.std;
const builtin = shared.builtin;
const aot_abi = shared.aot_abi;
pub const aot_builtin = shared.aot_builtin;
pub const BigInt = shared.BigInt;
const error_message = shared.error_message;
const unicode_case = shared.unicode_case;
const number_mod = shared.number_mod;
const string_mod = shared.string_mod;
const system_constant = shared.system_constant;
pub const crypto = shared.crypto;
const encoding = shared.encoding;
const zip_archive = shared.zip_archive;
const regexp = shared.regexp;
const markup = shared.markup;
const lexer = shared.lexer;
const josi = shared.josi;
const builtin_catalog = shared.builtin_catalog;
const dynamic_ir = shared.dynamic_ir;
const dynamic_interpreter = shared.dynamic_interpreter;
const dynamic_value = shared.dynamic_value;
pub const toml_temporal = shared.toml_temporal;

pub const lnako_aot_builtin_call = builtins.lnako_aot_builtin_call;
pub const lnako_aot_builtin_call_site = builtins.lnako_aot_builtin_call_site;
pub const lnako_aot_debug_breakpoint_wait_call = builtins.lnako_aot_debug_breakpoint_wait_call;
pub extern "c" fn fflush(stream: ?*std.c.FILE) c_int;
pub extern "c" fn time(timer: ?*i64) i64;

const AotWindowsStdout = shared.AotWindowsStdout;
pub const Tag = shared.Tag;
pub const AotPrimitiveHint = shared.AotPrimitiveHint;
const no_dispatch_call_id = shared.no_dispatch_call_id;
pub const safe_array_element_limit = shared.safe_array_element_limit;
pub const aot_timer_event_limit = shared.aot_timer_event_limit;

const trace_module = @import("trace.zig");

pub const DispatchTrace = trace_module.DispatchTrace;
pub const GlobalTrace = trace_module.GlobalTrace;
pub const LiteralTrace = trace_module.LiteralTrace;

const runtime_core_module = @import("runtime_core.zig");

pub const Value = runtime_core_module.Value;
pub const RootFrame = runtime_core_module.RootFrame;
pub const DictionaryEntry = runtime_core_module.DictionaryEntry;
pub const AotTomlTemporal = runtime_core_module.AotTomlTemporal;
pub const ByteKind = runtime_core_module.ByteKind;
pub const ByteBuffer = runtime_core_module.ByteBuffer;
pub const AotTimer = runtime_core_module.AotTimer;
pub const AotPromiseState = runtime_core_module.AotPromiseState;
pub const AotPromiseReactionMode = runtime_core_module.AotPromiseReactionMode;
pub const AotPromiseReaction = runtime_core_module.AotPromiseReaction;
pub const AotPromiseTask = runtime_core_module.AotPromiseTask;
pub const AotPromiseAllState = runtime_core_module.AotPromiseAllState;
pub const AotPromiseResolver = runtime_core_module.AotPromiseResolver;
pub const AotPromiseAllHandler = runtime_core_module.AotPromiseAllHandler;
pub const AotPromiseChainKind = runtime_core_module.AotPromiseChainKind;
pub const FunctionCallback = runtime_core_module.FunctionCallback;
pub const AotHttpRoute = runtime_core_module.AotHttpRoute;
pub const AotHttpHeader = runtime_core_module.AotHttpHeader;
pub const AotArchiveOperation = runtime_core_module.AotArchiveOperation;
pub const AotArchiveTask = runtime_core_module.AotArchiveTask;
pub const AotProcessMode = runtime_core_module.AotProcessMode;
pub const AotCommandResult = runtime_core_module.AotCommandResult;
pub const AotProcessTask = runtime_core_module.AotProcessTask;
pub const AotFileTaskOperation = runtime_core_module.AotFileTaskOperation;
pub const AotFileTask = runtime_core_module.AotFileTask;
pub const AotClientHttpResult = runtime_core_module.AotClientHttpResult;
pub const AotClientHttpMode = runtime_core_module.AotClientHttpMode;
pub const AotClientHttpBodyKind = runtime_core_module.AotClientHttpBodyKind;
pub const AotClientHttpTask = runtime_core_module.AotClientHttpTask;
pub const AotCsvDelimiterDefault = runtime_core_module.AotCsvDelimiterDefault;
pub const default_plugin_names = runtime_core_module.default_plugin_names;
pub const AotCsvState = runtime_core_module.AotCsvState;
pub const Arithmetic = runtime_core_module.Arithmetic;
pub const Comparison = runtime_core_module.Comparison;
pub const ShiftOperator = runtime_core_module.ShiftOperator;
pub const Object = runtime_core_module.Object;
pub const Runtime = runtime_core_module.Runtime;

const dynamic_module = @import("dynamic.zig");

pub const DynamicGlobal = dynamic_module.DynamicGlobal;
pub const DynamicPromiseBridge = dynamic_module.DynamicPromiseBridge;
pub const AotFunctionBridge = dynamic_module.AotFunctionBridge;
pub const DynamicInterpreterState = dynamic_module.DynamicInterpreterState;
pub const traceDynamicBridges = dynamic_module.traceDynamicBridges;
pub const dynamicGlobal = dynamic_module.dynamicGlobal;
pub const upsertDynamicGlobal = dynamic_module.upsertDynamicGlobal;
pub const removeAotFunctionBridge = dynamic_module.removeAotFunctionBridge;
pub const releaseAotFunctionBridge = dynamic_module.releaseAotFunctionBridge;
pub const callAotFunctionBridge = dynamic_module.callAotFunctionBridge;
pub const aotFunctionToDynamicValue = dynamic_module.aotFunctionToDynamicValue;
pub const dynamicPromiseToAotValue = dynamic_module.dynamicPromiseToAotValue;
pub const aotToDynamicValue = dynamic_module.aotToDynamicValue;
pub const dynamicToAotValue = dynamic_module.dynamicToAotValue;
pub const prepareDynamic = dynamic_module.prepareDynamic;
pub const syncDynamicGlobals = dynamic_module.syncDynamicGlobals;
pub const dynamicInterpreterState = dynamic_module.dynamicInterpreterState;
pub const nativePluginBuiltin = dynamic_module.nativePluginBuiltin;
pub const dynamicBuiltin = dynamic_module.dynamicBuiltin;
pub const concatAotValues = dynamic_module.concatAotValues;

const node_module = @import("node.zig");

pub const runAotExternal = node_module.runAotExternal;
pub const nodeProcessBuiltin = node_module.nodeProcessBuiltin;
pub const nodeBasenameWideFor = node_module.nodeBasenameWideFor;
pub const nodeNetworkAddressesBuiltin = node_module.nodeNetworkAddressesBuiltin;
pub const nodeEnvironmentBuiltin = node_module.nodeEnvironmentBuiltin;
pub const nodeProcessExitCode = node_module.nodeProcessExitCode;
pub const nodeCryptoBuiltin = node_module.nodeCryptoBuiltin;
pub const nodeDirectoryBuiltin = node_module.nodeDirectoryBuiltin;
pub const nodeTemporaryDirectoryPrefixAlloc = node_module.nodeTemporaryDirectoryPrefixAlloc;
pub const nodeCreateTemporaryDirectoryBuiltin = node_module.nodeCreateTemporaryDirectoryBuiltin;
pub const nodeMotherPathBuiltin = node_module.nodeMotherPathBuiltin;
pub const nodeEnvironmentValueBuiltin = node_module.nodeEnvironmentValueBuiltin;
pub const nodeEnvironmentListBuiltin = node_module.nodeEnvironmentListBuiltin;
pub const nodeCurrentDirectoryBuiltin = node_module.nodeCurrentDirectoryBuiltin;
pub const currentDirectoryAlloc = node_module.currentDirectoryAlloc;
pub const aotProcessEnvironment = node_module.aotProcessEnvironment;
pub const nodeChangeDirectoryBuiltin = node_module.nodeChangeDirectoryBuiltin;
pub const nodePathBuiltin = node_module.nodePathBuiltin;
pub const nodePathComponentBuiltin = node_module.nodePathComponentBuiltin;
pub const systemPathComponentBuiltin = node_module.systemPathComponentBuiltin;
pub const nodePathArgument = node_module.nodePathArgument;
pub const nodePathReceivedType = node_module.nodePathReceivedType;
pub const nodePathPrimitiveReceivedType = node_module.nodePathPrimitiveReceivedType;

const node_file_module = @import("node_file.zig");

pub const isNodeFileOperationCommand = node_file_module.isNodeFileOperationCommand;
pub const isNodeFileCallbackCommand = node_file_module.isNodeFileCallbackCommand;
pub const nodeFileExistenceBuiltin = node_file_module.nodeFileExistenceBuiltin;
pub const nodeFileReadBuiltin = node_file_module.nodeFileReadBuiltin;
pub const nodeEncodedFileReadBuiltin = node_file_module.nodeEncodedFileReadBuiltin;
pub const nodeFileSaveBuiltin = node_file_module.nodeFileSaveBuiltin;
pub const nodeEncodedFileSaveBuiltin = node_file_module.nodeEncodedFileSaveBuiltin;
pub const nodeEncodingName = node_file_module.nodeEncodingName;
pub const nodeEncodingValueBytesAlloc = node_file_module.nodeEncodingValueBytesAlloc;
pub const nodeEncodingBuiltin = node_file_module.nodeEncodingBuiltin;
pub const nodeFileCallbackBuiltin = node_file_module.nodeFileCallbackBuiltin;
pub const nodeFileOperationBuiltin = node_file_module.nodeFileOperationBuiltin;
pub const nodeFileListBuiltin = node_file_module.nodeFileListBuiltin;
pub const nodeFileDeleteBuiltin = node_file_module.nodeFileDeleteBuiltin;
pub const nodeFileCopyDefaultOverwrite = node_file_module.nodeFileCopyDefaultOverwrite;
pub const nodeFileCopyMoveBuiltin = node_file_module.nodeFileCopyMoveBuiltin;
pub const nodeFileSizeBuiltin = node_file_module.nodeFileSizeBuiltin;
pub const nodeFileInfoBuiltin = node_file_module.nodeFileInfoBuiltin;
pub const nodeFileInfoTrue = node_file_module.nodeFileInfoTrue;
pub const nodeFileInfoFalse = node_file_module.nodeFileInfoFalse;
pub const nodeEncodingSupportsBuiltin = node_file_module.nodeEncodingSupportsBuiltin;
pub const nodeStdinCallbackBuiltin = node_file_module.nodeStdinCallbackBuiltin;
pub const nodeStdinLineBuiltin = node_file_module.nodeStdinLineBuiltin;
pub const nodeStdinAllBuiltin = node_file_module.nodeStdinAllBuiltin;
pub const nodeStdinValueBuiltin = node_file_module.nodeStdinValueBuiltin;
pub const ensureAotStdin = node_file_module.ensureAotStdin;
pub const aotFileCopyMoveWithIo = node_file_module.aotFileCopyMoveWithIo;

const node_http_module = @import("node_http.zig");

pub const nodePostDataBuiltin = node_http_module.nodePostDataBuiltin;
pub const appendNodeUriComponent = node_http_module.appendNodeUriComponent;
pub const aotClientDictionaryGetAscii = node_http_module.aotClientDictionaryGetAscii;
pub const aotClientValueBytes = node_http_module.aotClientValueBytes;
pub const aotClientPrepareAjax = node_http_module.aotClientPrepareAjax;
pub const aotClientAppendUriComponent = node_http_module.aotClientAppendUriComponent;
pub const aotClientFormEncodedBody = node_http_module.aotClientFormEncodedBody;
pub const aotClientMultipartFields = node_http_module.aotClientMultipartFields;
pub const aotClientPreparePost = node_http_module.aotClientPreparePost;
pub const aotClientPrepareDiscord = node_http_module.aotClientPrepareDiscord;
pub const aotClientPrepareDiscordFile = node_http_module.aotClientPrepareDiscordFile;
pub const aotClientHttpMethod = node_http_module.aotClientHttpMethod;
pub const aotClientHttpRequest = node_http_module.aotClientHttpRequest;
pub const aotClientHttpBodyValue = node_http_module.aotClientHttpBodyValue;
pub const aotClientHttpResponseValue = node_http_module.aotClientHttpResponseValue;
pub const isAotHttpResponse = node_http_module.isAotHttpResponse;
pub const aotClientHttpResponseBody = node_http_module.aotClientHttpResponseBody;
pub const aotClientHttpResponseStatus = node_http_module.aotClientHttpResponseStatus;
pub const aotClientHttpBodyKind = node_http_module.aotClientHttpBodyKind;
pub const aotClientPrepareHttpCommand = node_http_module.aotClientPrepareHttpCommand;
pub const aotClientIsCallbackCommand = node_http_module.aotClientIsCallbackCommand;
pub const aotClientIsResponsePromiseCommand = node_http_module.aotClientIsResponsePromiseCommand;
pub const nodeHttpBuiltin = node_http_module.nodeHttpBuiltin;

const conversion_module = @import("conversion.zig");

pub const valueIndex = conversion_module.valueIndex;
pub const aotByteBufferAllowsStandardPrototype = conversion_module.aotByteBufferAllowsStandardPrototype;
pub const aotByteBufferScalarProperty = conversion_module.aotByteBufferScalarProperty;
pub const aotByteBufferReadOnlyProperty = conversion_module.aotByteBufferReadOnlyProperty;
pub const valueToNumber = conversion_module.valueToNumber;
pub const valueToNumberRuntime = conversion_module.valueToNumberRuntime;
pub const explicitRangeNumber = conversion_module.explicitRangeNumber;
pub const valueToParseFloatRuntime = conversion_module.valueToParseFloatRuntime;
pub const parseStringNumber = conversion_module.parseStringNumber;
pub const validDecimalNumber = conversion_module.validDecimalNumber;
pub const incrementNumber = conversion_module.incrementNumber;
pub const incrementValue = conversion_module.incrementValue;
pub const isString = conversion_module.isString;
pub const isObject = conversion_module.isObject;
pub const stringUtf8Alloc = conversion_module.stringUtf8Alloc;
pub const valueUtf16Alloc = conversion_module.valueUtf16Alloc;
pub const byteBufferUtf16Alloc = conversion_module.byteBufferUtf16Alloc;
pub const functionStringUtf16Alloc = conversion_module.functionStringUtf16Alloc;
pub const arrayUtf16Alloc = conversion_module.arrayUtf16Alloc;
pub const isAotObjectValue = conversion_module.isAotObjectValue;
pub const valueToPrimitive = conversion_module.valueToPrimitive;
pub const hostObjectToPrimitive = conversion_module.hostObjectToPrimitive;
pub const aotCustomObjectPrototypeProperty = conversion_module.aotCustomObjectPrototypeProperty;
pub const arrayToPrimitive = conversion_module.arrayToPrimitive;
pub const dictionaryToPrimitive = conversion_module.dictionaryToPrimitive;
pub const stringEqual = conversion_module.stringEqual;
pub const stringOrder = conversion_module.stringOrder;
pub const strictEqual = conversion_module.strictEqual;
pub const sameValue = conversion_module.sameValue;
pub const sameValueZero = conversion_module.sameValueZero;
pub const abstractEqual = conversion_module.abstractEqual;
pub const relationalOrder = conversion_module.relationalOrder;
pub const deepEqual = conversion_module.deepEqual;
pub const isJsonStringifyObject = conversion_module.isJsonStringifyObject;
pub const compareValues = conversion_module.compareValues;
pub const numberString = conversion_module.numberString;
pub const concat = conversion_module.concat;
pub const bigIntArithmetic = conversion_module.bigIntArithmetic;
pub const arithmetic = conversion_module.arithmetic;
pub const bigIntEqualsString = conversion_module.bigIntEqualsString;
pub const compareBigIntString = conversion_module.compareBigIntString;
pub const bigIntFromString = conversion_module.bigIntFromString;
pub const shift = conversion_module.shift;
pub const bitNot = conversion_module.bitNot;
pub const valueTruthy = conversion_module.valueTruthy;
pub const toInt32 = conversion_module.toInt32;
pub const toUint32 = conversion_module.toUint32;
pub const bigIntEqualsNumber = conversion_module.bigIntEqualsNumber;
pub const compareBigIntNumber = conversion_module.compareBigIntNumber;
pub const invertOrder = conversion_module.invertOrder;
pub const repeatCount = conversion_module.repeatCount;
pub const sameKey = conversion_module.sameKey;
pub const staticUtf8EqualsUtf16 = conversion_module.staticUtf8EqualsUtf16;
pub const staticUtf8 = conversion_module.staticUtf8;

const regexp_module = @import("regexp.zig");

pub const RegexpCallResult = regexp_module.RegexpCallResult;
pub const regexpCommandName = regexp_module.regexpCommandName;
pub const setRegexpCompileFailureMessage = regexp_module.setRegexpCompileFailureMessage;
pub const regexpBuiltin = regexp_module.regexpBuiltin;

/// Dedicated ABI because regexp match/extract update the system global
/// `抽出文字列` in addition to returning their normal value.
const json_module = @import("json.zig");

pub const appendAsciiUnits = json_module.appendAsciiUnits;
pub const appendUtf8Units = json_module.appendUtf8Units;
pub const jsonEncodeBuiltin = json_module.jsonEncodeBuiltin;
pub const jsonDecodeBuiltin = json_module.jsonDecodeBuiltin;
pub const jsonAotContainerCount = json_module.jsonAotContainerCount;

pub extern "c" fn putchar(character: c_int) c_int;

const display_module = @import("display.zig");

pub const writeUtf16 = display_module.writeUtf16;
pub const valueUtf8LossyAlloc = display_module.valueUtf8LossyAlloc;
pub const utf16UnitsToUtf8LossyAlloc = display_module.utf16UnitsToUtf8LossyAlloc;
pub const appendDisplayLog = display_module.appendDisplayLog;
pub const emitDisplayLine = display_module.emitDisplayLine;
pub const displayValue = display_module.displayValue;
pub const continueDisplayValue = display_module.continueDisplayValue;
pub const joinValuesUtf8Alloc = display_module.joinValuesUtf8Alloc;
pub const displayMany = display_module.displayMany;
pub const configureHatenaBuiltin = display_module.configureHatenaBuiltin;
pub const configureInterruptBuiltin = display_module.configureInterruptBuiltin;
pub const invokeHatenaNamedCallback = display_module.invokeHatenaNamedCallback;
pub const invokeHatenaCallbacks = display_module.invokeHatenaCallbacks;
pub const writeAllValues = display_module.writeAllValues;
pub const isStdioCommand = display_module.isStdioCommand;
pub const isNodeProcessCommand = display_module.isNodeProcessCommand;
pub const isNodeHttpCommand = display_module.isNodeHttpCommand;
pub const isArchiveCommand = display_module.isArchiveCommand;
pub const isPluginManagementCommand = display_module.isPluginManagementCommand;
pub const stdioBuiltin = display_module.stdioBuiltin;
pub const pluginManagementArgument = display_module.pluginManagementArgument;
pub const pluginManagementBuiltin = display_module.pluginManagementBuiltin;

const http_server_module = @import("http_server.zig");

pub const isHttpServerCommand = http_server_module.isHttpServerCommand;
pub const httpServerBuiltin = http_server_module.httpServerBuiltin;
pub const aotHttpDictionarySetUtf8 = http_server_module.aotHttpDictionarySetUtf8;
pub const pollAotHttpServer = http_server_module.pollAotHttpServer;

const async_module = @import("async.zig");

pub const sleepAotUntil = async_module.sleepAotUntil;
pub const runAotShellCommand = async_module.runAotShellCommand;
pub const aotRuntimeIo = async_module.aotRuntimeIo;
pub const writeAotStderr = async_module.writeAotStderr;
pub const waitAotMilliseconds = async_module.waitAotMilliseconds;
pub const queueAotProcess = async_module.queueAotProcess;
pub const queueAotFileTask = async_module.queueAotFileTask;
pub const readyAotProcessTaskIndex = async_module.readyAotProcessTaskIndex;
pub const readyAotFileTaskIndex = async_module.readyAotFileTaskIndex;
pub const writeAotAjaxReceiveError = async_module.writeAotAjaxReceiveError;
pub const aotArchiveExecute = async_module.aotArchiveExecute;
pub const drainAotProcessTasks = async_module.drainAotProcessTasks;
pub const drainAotFileTasks = async_module.drainAotFileTasks;
pub const drainAotArchiveTasks = async_module.drainAotArchiveTasks;
pub const drainAotPromiseTasks = async_module.drainAotPromiseTasks;
pub const drainAotNativePluginTasks = async_module.drainAotNativePluginTasks;
pub const drainAotClientHttpTasks = async_module.drainAotClientHttpTasks;
pub const drainAotEvents = async_module.drainAotEvents;
pub const drainAotTimers = async_module.drainAotTimers;
pub const timerBuiltin = async_module.timerBuiltin;
pub const timerWaitBuiltin = async_module.timerWaitBuiltin;
pub const countAotEvent = async_module.countAotEvent;
pub const earliestAotTimerIndex = async_module.earliestAotTimerIndex;
pub const executeAotTimer = async_module.executeAotTimer;
pub const aotPromiseObject = async_module.aotPromiseObject;
pub const aotPromiseValue = async_module.aotPromiseValue;
pub const createAotPromise = async_module.createAotPromise;
pub const aotPromiseThen = async_module.aotPromiseThen;
pub const resolveAotPromise = async_module.resolveAotPromise;
pub const rejectAotPromise = async_module.rejectAotPromise;
pub const enqueueAotPromiseReaction = async_module.enqueueAotPromiseReaction;
pub const enqueueAotPromiseReactions = async_module.enqueueAotPromiseReactions;
pub const createAotPromiseResolver = async_module.createAotPromiseResolver;
pub const createAotPromiseWithExecutor = async_module.createAotPromiseWithExecutor;
pub const chainAotPromise = async_module.chainAotPromise;
pub const bundleAotPromises = async_module.bundleAotPromises;
pub const createAotPromiseAllHandler = async_module.createAotPromiseAllHandler;
pub const promiseAotBuiltin = async_module.promiseAotBuiltin;
pub const awaitAotPromise = async_module.awaitAotPromise;
pub const forwardAotPromiseTask = async_module.forwardAotPromiseTask;
pub const executeAotPromiseTask = async_module.executeAotPromiseTask;
pub const callbackFailureReason = async_module.callbackFailureReason;
pub const destroyAotPromiseAllState = async_module.destroyAotPromiseAllState;
pub const handleAotPromiseAll = async_module.handleAotPromiseAll;

const host_module = @import("host.zig");

pub const stringArrayBuiltin = host_module.stringArrayBuiltin;
pub const systemFunctionExistsBuiltin = host_module.systemFunctionExistsBuiltin;
pub const utf16FailureMessageUtf8Alloc = host_module.utf16FailureMessageUtf8Alloc;
pub const pendingExceptionMessageUtf8Alloc = host_module.pendingExceptionMessageUtf8Alloc;
pub const writeBytes = host_module.writeBytes;
pub const AotHttpPathStat = host_module.AotHttpPathStat;
pub const runtimeFailure = host_module.runtimeFailure;
pub const installAotInterrupt = host_module.installAotInterrupt;
pub const pollAotInterrupt = host_module.pollAotInterrupt;
pub const debugDisplayBuiltin = host_module.debugDisplayBuiltin;
pub const normalizeDebugSourcePath = host_module.normalizeDebugSourcePath;
pub const promiseSentinel = host_module.promiseSentinel;
pub const byteBufferUnboundSliceCallback = host_module.byteBufferUnboundSliceCallback;
pub const builtinDispatchRoute = host_module.builtinDispatchRoute;
pub const typeNameValue = host_module.typeNameValue;
pub const parseIntBuiltin = host_module.parseIntBuiltin;
pub const runtimeUtf8String = host_module.runtimeUtf8String;
pub const runtimeUtf8StringLossy = host_module.runtimeUtf8StringLossy;
pub const debugBreakpointWaitBuiltin = host_module.debugBreakpointWaitBuiltin;
pub const measureCallableBuiltin = host_module.measureCallableBuiltin;
pub const shouldRegisterNamedFunction = host_module.shouldRegisterNamedFunction;
pub const systemGlobalFunctionNamesBuiltin = host_module.systemGlobalFunctionNamesBuiltin;
pub const aotOsName = host_module.aotOsName;
pub const aotArchitectureName = host_module.aotArchitectureName;
pub const radixBuiltin = host_module.radixBuiltin;
pub const rgbBuiltin = host_module.rgbBuiltin;
pub const rangeBuiltin = host_module.rangeBuiltin;
pub const repeatMultiplyBuiltin = host_module.repeatMultiplyBuiltin;

pub var active_runtime: ?Runtime = null;
pub var aot_interrupt_requested = std.atomic.Value(bool).init(false);

const math_module = @import("math.zig");

pub const parseFloatBuiltin = math_module.parseFloatBuiltin;
pub const mathBuiltin = math_module.mathBuiltin;
pub const initialRandomState = math_module.initialRandomState;
pub const nextRandom = math_module.nextRandom;

const datetime_module = @import("datetime.zig");

pub const currentTimeMilliseconds = datetime_module.currentTimeMilliseconds;
pub const monotonicTimeMilliseconds = datetime_module.monotonicTimeMilliseconds;
pub const eraDataBuiltin = datetime_module.eraDataBuiltin;
pub const datetimeBuiltin = datetime_module.datetimeBuiltin;
pub const datetimeAddDatePluginEpoch = datetime_module.datetimeAddDatePluginEpoch;
pub const datetimeAddDateSystemEpoch = datetime_module.datetimeAddDateSystemEpoch;
pub const datetimeConstructLocal = datetime_module.datetimeConstructLocal;
pub const datetimeFieldsFromEpoch = datetime_module.datetimeFieldsFromEpoch;

const caniuse_module = @import("caniuse.zig");

pub const caniuseAgentsBuiltin = caniuse_module.caniuseAgentsBuiltin;
pub const caniuseBrowsersBuiltin = caniuse_module.caniuseBrowsersBuiltin;

const url_path_module = @import("url_path.zig");

pub const urlBuiltin = url_path_module.urlBuiltin;
pub const pathBuiltin = url_path_module.pathBuiltin;
pub const pathExtractExtensionBuiltin = url_path_module.pathExtractExtensionBuiltin;
pub const pathChangeExtensionBuiltin = url_path_module.pathChangeExtensionBuiltin;
pub const pathAddTrailingSeparatorBuiltin = url_path_module.pathAddTrailingSeparatorBuiltin;
pub const pathRemoveTrailingSeparatorBuiltin = url_path_module.pathRemoveTrailingSeparatorBuiltin;
pub const pathSeparatorUnit = url_path_module.pathSeparatorUnit;
pub const pathBasenameUnits = url_path_module.pathBasenameUnits;
pub const pathAllExtensionUnits = url_path_module.pathAllExtensionUnits;
pub const urlEncodeBuiltin = url_path_module.urlEncodeBuiltin;
pub const urlDecodeBuiltin = url_path_module.urlDecodeBuiltin;
pub const urlDecodeUnits = url_path_module.urlDecodeUnits;
pub const urlParametersBuiltin = url_path_module.urlParametersBuiltin;
pub const base64EncodeBuiltin = url_path_module.base64EncodeBuiltin;
pub const base64DecodeBuiltin = url_path_module.base64DecodeBuiltin;
pub const urlIsComponentByte = url_path_module.urlIsComponentByte;
pub const urlHexDigit = url_path_module.urlHexDigit;
pub const base64Digit = url_path_module.base64Digit;

const kansuji_module = @import("kansuji.zig");

pub const kansujiBuiltin = kansuji_module.kansujiBuiltin;
pub const kansujiToKanjiBuiltin = kansuji_module.kansujiToKanjiBuiltin;
pub const kansujiToArabicBuiltin = kansuji_module.kansujiToArabicBuiltin;
pub const kansujiMatchAny = kansuji_module.kansujiMatchAny;
pub const kansujiMatchDigit = kansuji_module.kansujiMatchDigit;
pub const kansujiAddDefaultedBase = kansuji_module.kansujiAddDefaultedBase;
pub const kansujiAddFinalBase = kansuji_module.kansujiAddFinalBase;
pub const kansujiAddPair = kansuji_module.kansujiAddPair;
pub const kansujiAddBig = kansuji_module.kansujiAddBig;
pub const kansujiFullwidthDigits = kansuji_module.kansujiFullwidthDigits;
pub const kansujiExpandDecimal = kansuji_module.kansujiExpandDecimal;
pub const kansujiValidExponentMantissa = kansuji_module.kansujiValidExponentMantissa;
pub const kansujiValidDecimal = kansuji_module.kansujiValidDecimal;
pub const kansujiIsJsNumberString = kansuji_module.kansujiIsJsNumberString;
pub const kansujiTrimJsWhitespace = kansuji_module.kansujiTrimJsWhitespace;
pub const kansujiIsJsWhitespace = kansuji_module.kansujiIsJsWhitespace;
pub const kansujiKanjiDigit = kansuji_module.kansujiKanjiDigit;
pub const kansujiAllAsciiDigits = kansuji_module.kansujiAllAsciiDigits;
pub const kansujiAllAsciiDigitUnits = kansuji_module.kansujiAllAsciiDigitUnits;

const text_module = @import("text.zig");

pub const csvBuiltin = text_module.csvBuiltin;
pub const csvParse = text_module.csvParse;
pub const csvStringify = text_module.csvStringify;
pub const tomlBuiltin = text_module.tomlBuiltin;
pub const tomlParse = text_module.tomlParse;
pub const tomlStringify = text_module.tomlStringify;
pub const markupBuiltin = text_module.markupBuiltin;
pub const courtesyBuiltin = text_module.courtesyBuiltin;
pub const systemExecutionBuiltin = text_module.systemExecutionBuiltin;

const node_path_module = @import("node_path.zig");

pub const isWindowsDriveLetter = node_path_module.isWindowsDriveLetter;
pub const isWindowsDriveLetterWide = node_path_module.isWindowsDriveLetterWide;
pub const nodeBasename = node_path_module.nodeBasename;
pub const nodeBasenameFor = node_path_module.nodeBasenameFor;
pub const nodeDirname = node_path_module.nodeDirname;
pub const nodeDirnameFor = node_path_module.nodeDirnameFor;
pub const nodeDirnameWindowsFor = node_path_module.nodeDirnameWindowsFor;
pub const nodePathSeparator = node_path_module.nodePathSeparator;
pub const nodePathSeparatorWide = node_path_module.nodePathSeparatorWide;

const search_module = @import("search.zig");

pub const codePointCount = search_module.codePointCount;
pub const codePointLength = search_module.codePointLength;
pub const codePointFindStringBuiltin = search_module.codePointFindStringBuiltin;
pub const search_element_limit = search_module.search_element_limit;
pub const SearchElements = search_module.SearchElements;
pub const SearchElement = search_module.SearchElement;
pub const searchArrayFromLength = search_module.searchArrayFromLength;
pub const appendStringSearchElements = search_module.appendStringSearchElements;
pub const appendDictionarySearchElements = search_module.appendDictionarySearchElements;
pub const byteBufferArrayLikeProperty = search_module.byteBufferArrayLikeProperty;
pub const appendArrayBufferSearchElements = search_module.appendArrayBufferSearchElements;
pub const searchIndexKey = search_module.searchIndexKey;
pub const appendSearchElements = search_module.appendSearchElements;
pub const joinedSearchElementsEqual = search_module.joinedSearchElementsEqual;
pub const codePointFindBuiltin = search_module.codePointFindBuiltin;
pub const stringBoundaryBuiltin = search_module.stringBoundaryBuiltin;
pub const requireStringReceiver = search_module.requireStringReceiver;
pub const elementCountBuiltin = search_module.elementCountBuiltin;

const primitive_module = @import("primitive.zig");

pub const addParsedBuiltin = primitive_module.addParsedBuiltin;
pub const sumParsedBuiltin = primitive_module.sumParsedBuiltin;
pub const toBigIntBuiltin = primitive_module.toBigIntBuiltin;
pub const jsAdd = primitive_module.jsAdd;
pub const CutResult = primitive_module.CutResult;
pub const cutLengthProperty = primitive_module.cutLengthProperty;
pub const dictionaryLengthValue = primitive_module.dictionaryLengthValue;
pub const cutEndIndex = primitive_module.cutEndIndex;
pub const cutBuiltin = primitive_module.cutBuiltin;
pub const sequentialAddBuiltin = primitive_module.sequentialAddBuiltin;
pub const chrBuiltin = primitive_module.chrBuiltin;
pub const codePointStringBuiltin = primitive_module.codePointStringBuiltin;
pub const ascBuiltin = primitive_module.ascBuiltin;
pub const firstCodePointBuiltin = primitive_module.firstCodePointBuiltin;
pub const stringInsertBuiltin = primitive_module.stringInsertBuiltin;
pub const stringSearchBuiltin = primitive_module.stringSearchBuiltin;
pub const codePointOffsetBuiltin = primitive_module.codePointOffsetBuiltin;
pub const stringCollectionIndex = primitive_module.stringCollectionIndex;
pub const appendBuiltin = primitive_module.appendBuiltin;
pub const joinBuiltin = primitive_module.joinBuiltin;
pub const arrayJoinBuiltin = primitive_module.arrayJoinBuiltin;
pub const arraySearchBuiltin = primitive_module.arraySearchBuiltin;

const sort_module = @import("sort.zig");

pub const arrayOrderingBuiltin = sort_module.arrayOrderingBuiltin;
pub const arrayShuffleBuiltin = sort_module.arrayShuffleBuiltin;
pub const arrayCallbackBuiltin = sort_module.arrayCallbackBuiltin;
pub const stableArrayCallbackSort = sort_module.stableArrayCallbackSort;
pub const v8_small_callback_sort_limit = sort_module.v8_small_callback_sort_limit;
pub const V8TableSortContext = sort_module.V8TableSortContext;
pub const V8SortContext = sort_module.V8SortContext;
pub const compareV8Sort = sort_module.compareV8Sort;
pub const v8SmallArrayCallbackSort = sort_module.v8SmallArrayCallbackSort;
pub const v8CopyArrayRange = sort_module.v8CopyArrayRange;
pub const v8ComputeMinRunLengthArray = sort_module.v8ComputeMinRunLengthArray;
pub const v8CountAndMakeRunArrayCallback = sort_module.v8CountAndMakeRunArrayCallback;
pub const v8BinaryInsertionSortArrayCallback = sort_module.v8BinaryInsertionSortArrayCallback;
pub const v8GallopLeftArrayCallback = sort_module.v8GallopLeftArrayCallback;
pub const v8GallopRightArrayCallback = sort_module.v8GallopRightArrayCallback;
pub const v8MergeLowArrayCallback = sort_module.v8MergeLowArrayCallback;
pub const v8MergeHighArrayCallback = sort_module.v8MergeHighArrayCallback;
pub const v8MergeAtArrayCallback = sort_module.v8MergeAtArrayCallback;
pub const v8RunInvariantEstablishedArray = sort_module.v8RunInvariantEstablishedArray;
pub const v8MergeCollapseArrayCallback = sort_module.v8MergeCollapseArrayCallback;
pub const v8MergeForceCollapseArrayCallback = sort_module.v8MergeForceCollapseArrayCallback;
pub const v8TimSortArrayCallback = sort_module.v8TimSortArrayCallback;
pub const compareAotCallback = sort_module.compareAotCallback;
pub const invokeAotCallback = sort_module.invokeAotCallback;
pub const resolveAotCallback = sort_module.resolveAotCallback;
pub const registeredFunctionMatches = sort_module.registeredFunctionMatches;
pub const stableArraySort = sort_module.stableArraySort;
pub const compareArraySortValues = sort_module.compareArraySortValues;
pub const utf16Order = sort_module.utf16Order;

const collection_module = @import("collection.zig");

pub const arrayItems = collection_module.arrayItems;
pub const spliceIndexRuntime = collection_module.spliceIndexRuntime;
pub const spliceIndexNumber = collection_module.spliceIndexNumber;
pub const spliceCountRuntime = collection_module.spliceCountRuntime;
pub const spliceCountNumber = collection_module.spliceCountNumber;
pub const dictionaryOwnProperty = collection_module.dictionaryOwnProperty;
pub const dictionaryPrototypeProperty = collection_module.dictionaryPrototypeProperty;
pub const dictionaryPrototypeBlocksStandard = collection_module.dictionaryPrototypeBlocksStandard;
pub const arrayPrototypeProperty = collection_module.arrayPrototypeProperty;
pub const arrayPrototypeBlocksStandard = collection_module.arrayPrototypeBlocksStandard;
pub const dictionaryProperty = collection_module.dictionaryProperty;
pub const aotCanonicalArrayIndex = collection_module.aotCanonicalArrayIndex;
pub const aotDictionaryOrder = collection_module.aotDictionaryOrder;
pub const aotDictionaryOrderBefore = collection_module.aotDictionaryOrderBefore;
pub const aotPropertyKeysEqual = collection_module.aotPropertyKeysEqual;
pub const aotEnumerableKeyWasYielded = collection_module.aotEnumerableKeyWasYielded;
pub const aotEnumerableDictionaryEntries = collection_module.aotEnumerableDictionaryEntries;
pub const aotPropertyKeyEqual = collection_module.aotPropertyKeyEqual;
pub const dictionaryKeysBuiltin = collection_module.dictionaryKeysBuiltin;
pub const dictionaryValuesBuiltin = collection_module.dictionaryValuesBuiltin;
pub const dictionaryRemoveBuiltin = collection_module.dictionaryRemoveBuiltin;
pub const byteBufferIndexDeleteFailure = collection_module.byteBufferIndexDeleteFailure;
pub const dictionaryHasBuiltin = collection_module.dictionaryHasBuiltin;
pub const stringValuesEqual = collection_module.stringValuesEqual;
pub const arrayRange = collection_module.arrayRange;
pub const spliceArrayBuiltin = collection_module.spliceArrayBuiltin;
pub const insertValuesAssumeCapacity = collection_module.insertValuesAssumeCapacity;
pub const insertPresenceAssumeCapacity = collection_module.insertPresenceAssumeCapacity;
pub const arrayInsertBuiltin = collection_module.arrayInsertBuiltin;
pub const arrayInsertManyBuiltin = collection_module.arrayInsertManyBuiltin;
pub const arrayCutBuiltin = collection_module.arrayCutBuiltin;
pub const arrayTakeBuiltin = collection_module.arrayTakeBuiltin;
pub const arrayPopBuiltin = collection_module.arrayPopBuiltin;
pub const arrayPushBuiltin = collection_module.arrayPushBuiltin;
pub const arrayMutationBuiltin = collection_module.arrayMutationBuiltin;
pub const sliceIndex = collection_module.sliceIndex;
pub const directIndex = collection_module.directIndex;
pub const bigIntPropertyIndex = collection_module.bigIntPropertyIndex;
pub const charAtIndex = collection_module.charAtIndex;
pub const sliceRange = collection_module.sliceRange;
pub const substringRange = collection_module.substringRange;
pub const arrayRangeCopyBuiltin = collection_module.arrayRangeCopyBuiltin;
pub const referenceBuiltin = collection_module.referenceBuiltin;
pub const invalidStringRangeBuiltin = collection_module.invalidStringRangeBuiltin;
pub const appendAotArraySlot = collection_module.appendAotArraySlot;
pub const arrayAddBuiltin = collection_module.arrayAddBuiltin;
pub const arrayExtremumBuiltin = collection_module.arrayExtremumBuiltin;
pub const isNegativeZero = collection_module.isNegativeZero;
pub const arraySumBuiltin = collection_module.arraySumBuiltin;
pub const arraySwapBuiltin = collection_module.arraySwapBuiltin;
pub const fillArrayLength = collection_module.fillArrayLength;
pub const arraySequenceBuiltin = collection_module.arraySequenceBuiltin;
pub const arrayFillBuiltin = collection_module.arrayFillBuiltin;
pub const validateFillDimensions = collection_module.validateFillDimensions;
pub const cloneFillValue = collection_module.cloneFillValue;
pub const arrayFillAtDepth = collection_module.arrayFillAtDepth;
pub const explodeBuiltin = collection_module.explodeBuiltin;
pub const refrainBuiltin = collection_module.refrainBuiltin;
pub const occurrenceBuiltin = collection_module.occurrenceBuiltin;
pub const occurrenceCountBuiltin = collection_module.occurrenceCountBuiltin;
pub const substringBuiltin = collection_module.substringBuiltin;
pub const substringNumberBuiltin = collection_module.substringNumberBuiltin;
pub const sliceIndexBuiltin = collection_module.sliceIndexBuiltin;
pub const splitBuiltin = collection_module.splitBuiltin;
pub const appendStringPart = collection_module.appendStringPart;
pub const stringRemoveBuiltin = collection_module.stringRemoveBuiltin;
pub const spliceDeleteCountBuiltin = collection_module.spliceDeleteCountBuiltin;
pub const trimBuiltin = collection_module.trimBuiltin;
pub const unicodeCaseBuiltin = collection_module.unicodeCaseBuiltin;
pub const isFinalSigmaBuiltin = collection_module.isFinalSigmaBuiltin;
pub const appendCodePointBuiltin = collection_module.appendCodePointBuiltin;

const table_module = @import("table.zig");

pub const tableAsciiUnitsEqual = table_module.tableAsciiUnitsEqual;
pub const tableInheritedMethodName = table_module.tableInheritedMethodName;
pub const tableBufferEnumerableFunctionName = table_module.tableBufferEnumerableFunctionName;
pub const tableInheritedFunctionWithCallback = table_module.tableInheritedFunctionWithCallback;
pub const tableInheritedFunction = table_module.tableInheritedFunction;
pub const tableInheritedByteBufferMethod = table_module.tableInheritedByteBufferMethod;
pub const tableInheritedProperty = table_module.tableInheritedProperty;
pub const tableRowProperty = table_module.tableRowProperty;
pub const setTableRowPropertyFailure = table_module.setTableRowPropertyFailure;
pub const tablePropertyKeyEqual = table_module.tablePropertyKeyEqual;
pub const tablePropertyIndex = table_module.tablePropertyIndex;
pub const tableColumnCountBuiltin = table_module.tableColumnCountBuiltin;
pub const tableSearchBuiltin = table_module.tableSearchBuiltin;
pub const tableColumnIterationCount = table_module.tableColumnIterationCount;
pub const tableTransposeBuiltin = table_module.tableTransposeBuiltin;
pub const tableDictionaryHasKey = table_module.tableDictionaryHasKey;
pub const tableIsObjectPrototypeKey = table_module.tableIsObjectPrototypeKey;
pub const tableUniqueBuiltin = table_module.tableUniqueBuiltin;
pub const tableInsertColumnBuiltin = table_module.tableInsertColumnBuiltin;
pub const aotByteBufferSlice = table_module.aotByteBufferSlice;
pub const tableDeleteColumnBuiltin = table_module.tableDeleteColumnBuiltin;
pub const tableColumnSumBuiltin = table_module.tableColumnSumBuiltin;
pub const tableRegexpPatternUnitsAlloc = table_module.tableRegexpPatternUnitsAlloc;
pub const tableRegexpSearchBuiltin = table_module.tableRegexpSearchBuiltin;
pub const tableRegexpPickupBuiltin = table_module.tableRegexpPickupBuiltin;
pub const incrementTableSearchRow = table_module.incrementTableSearchRow;
pub const compareTableRowsBuiltin = table_module.compareTableRowsBuiltin;
pub const tableSortBuiltin = table_module.tableSortBuiltin;
pub const v8SmallTableSortBuiltin = table_module.v8SmallTableSortBuiltin;
pub const tableBuiltin = table_module.tableBuiltin;
pub const deepCloneBuiltin = table_module.deepCloneBuiltin;
pub const deepCloneValue = table_module.deepCloneValue;
pub const CloneState = table_module.CloneState;
pub const table_byte_buffer_buffer_enumerable_property_names = table_module.table_byte_buffer_buffer_enumerable_property_names;

const string_module = @import("string.zig");

pub const kanaOffsetBuiltin = string_module.kanaOffsetBuiltin;
pub const asciiWidthBuiltin = string_module.asciiWidthBuiltin;
pub const kanaWidthBuiltin = string_module.kanaWidthBuiltin;
pub const widthBuiltin = string_module.widthBuiltin;
pub const currencyBuiltin = string_module.currencyBuiltin;
pub const padBuiltin = string_module.padBuiltin;
pub const stringPredicateBuiltin = string_module.stringPredicateBuiltin;
pub const numberSequenceBuiltin = string_module.numberSequenceBuiltin;
pub const isAsciiDigitBuiltin = string_module.isAsciiDigitBuiltin;
pub const isSequenceDigitBuiltin = string_module.isSequenceDigitBuiltin;
pub const isSequenceSignBuiltin = string_module.isSequenceSignBuiltin;
pub const kanaMapBuiltin = string_module.kanaMapBuiltin;
pub const kanaMapDictionaryFullWidthBuiltin = string_module.kanaMapDictionaryFullWidthBuiltin;
pub const kanaMapDictionaryHalfWidthBuiltin = string_module.kanaMapDictionaryHalfWidthBuiltin;
pub const unitIndexBuiltin = string_module.unitIndexBuiltin;
pub const indexOfUnitsBuiltin = string_module.indexOfUnitsBuiltin;
pub const replaceBuiltin = string_module.replaceBuiltin;
pub const appendFirstReplacementBuiltin = string_module.appendFirstReplacementBuiltin;

pub fn numberValue(number: f64) Value {
    return .{ .tag = @intFromEnum(Tag.number), .payload = @bitCast(number) };
}

pub fn staticStringValue(comptime text: [:0]const u8) Value {
    return .{ .tag = @intFromEnum(Tag.static_utf8_string), .payload = @intFromPtr(text.ptr) };
}

const values_module = @import("values.zig");
const instructions_module = @import("instructions.zig");
const functions_module = @import("functions.zig");

pub const lnako_aot_string_new = values_module.lnako_aot_string_new;
pub const lnako_aot_print_utf16 = values_module.lnako_aot_print_utf16;
pub const lnako_aot_print_number = values_module.lnako_aot_print_number;
pub const lnako_aot_bigint_new = values_module.lnako_aot_bigint_new;
pub const lnako_aot_print_bigint = values_module.lnako_aot_print_bigint;
pub const lnako_aot_print_collection = values_module.lnako_aot_print_collection;
pub const lnako_aot_display_value = values_module.lnako_aot_display_value;
pub const lnako_aot_array_new = values_module.lnako_aot_array_new;
pub const lnako_aot_dictionary_new = values_module.lnako_aot_dictionary_new;
pub const lnako_aot_caniuse_agents_new = values_module.lnako_aot_caniuse_agents_new;
pub const lnako_aot_era_data_new = values_module.lnako_aot_era_data_new;

pub const lnako_aot_bigint_truthy = instructions_module.lnako_aot_bigint_truthy;
pub const lnako_aot_arithmetic = instructions_module.lnako_aot_arithmetic;
pub const lnako_aot_compare = instructions_module.lnako_aot_compare;
pub const lnako_aot_shift = instructions_module.lnako_aot_shift;
pub const lnako_aot_concat = instructions_module.lnako_aot_concat;
pub const lnako_aot_increment = instructions_module.lnako_aot_increment;
pub const lnako_aot_index_get = instructions_module.lnako_aot_index_get;
pub const lnako_aot_index_set = instructions_module.lnako_aot_index_set;
pub const lnako_aot_destructure_get = instructions_module.lnako_aot_destructure_get;
pub const lnako_aot_iterator_new = instructions_module.lnako_aot_iterator_new;
pub const lnako_aot_iterator_has_next = instructions_module.lnako_aot_iterator_has_next;
pub const lnako_aot_iterator_next = instructions_module.lnako_aot_iterator_next;
pub const lnako_aot_binding_cell_new = instructions_module.lnako_aot_binding_cell_new;
pub const lnako_aot_binding_cell_value = instructions_module.lnako_aot_binding_cell_value;
pub const lnako_aot_cut = instructions_module.lnako_aot_cut;
pub const lnako_aot_cut_site = instructions_module.lnako_aot_cut_site;

pub const lnako_aot_native_plugin_register = functions_module.lnako_aot_native_plugin_register;
pub const lnako_aot_dynamic_global_register = functions_module.lnako_aot_dynamic_global_register;
pub const lnako_aot_dynamic_call = functions_module.lnako_aot_dynamic_call;
pub const lnako_aot_native_plugin_call = functions_module.lnako_aot_native_plugin_call;
pub const lnako_aot_function_new = functions_module.lnako_aot_function_new;
pub const lnako_aot_function_new_named = functions_module.lnako_aot_function_new_named;
pub const lnako_aot_function_capture = functions_module.lnako_aot_function_capture;
pub const lnako_aot_function_call = functions_module.lnako_aot_function_call;
