const std = @import("std");

/// なでしこ3 v3.7.24の標準cnako命令名。tools/sync_compat.mjsの固定データから生成。
pub const names = [_][]const u8{
    "ナデシコバージョン",
    "ナデシコ言語バージョン",
    "ナデシコエンジン",
    "ナデシコ種類",
    "はい",
    "いいえ",
    "真",
    "偽",
    "永遠",
    "オン",
    "オフ",
    "改行",
    "タブ",
    "カッコ",
    "カッコ閉",
    "波カッコ",
    "波カッコ閉",
    "OK",
    "NG",
    "キャンセル",
    "TRUE",
    "FALSE",
    "true",
    "false",
    "PI",
    "空",
    "NULL",
    "undefined",
    "未定義",
    "エラーメッセージ",
    "対象",
    "対象キー",
    "回数",
    "CR",
    "LF",
    "非数",
    "無限大",
    "戻値無",
    "戻値有",
    "空配列",
    "空辞書",
    "空ハッシュ",
    "空オブジェクト",
    "真偽判定",
    "ください",
    "お願",
    "です",
    "拝啓",
    "敬具",
    "礼節レベル取得",
    "JS実行",
    "JSオブジェクト取得",
    "JS関数実行",
    "ASYNC",
    "AWAIT実行",
    "JSメソッド実行",
    "ナデシコ",
    "ナデシコ続",
    "実行",
    "実行時間計測",
    "終",
    "デバッグ表示",
    "ハテナ関数設定",
    "ハテナ関数実行",
    "エラー発生",
    "__DEBUG",
    "__DEBUG強制待機",
    "__DEBUGブレイクポイント一覧",
    "__DEBUG待機フラグ",
    "__DEBUG_BP_WAIT",
    "グローバル関数一覧取得",
    "システム関数一覧取得",
    "システム関数存在",
    "プラグイン一覧取得",
    "モジュール一覧取得",
    "助詞一覧取得",
    "予約語一覧取得",
    "プラグイン名",
    "プラグイン名設定",
    "名前空間",
    "名前空間設定",
    "名前空間ポップ",
    "足",
    "合計",
    "引",
    "掛",
    "倍",
    "割",
    "割余",
    "偶数",
    "奇数",
    "二乗",
    "べき乗",
    "以上",
    "以下",
    "未満",
    "超",
    "等",
    "等無",
    "一致",
    "不一致",
    "範囲内",
    "範囲",
    "連続加算",
    "MAX",
    "最大値",
    "MIN",
    "最小値",
    "CLAMP",
    "論理OR",
    "論理AND",
    "論理NOT",
    "OR",
    "AND",
    "XOR",
    "NOT",
    "SHIFT_L",
    "SHIFT_R",
    "SHIFT_UR",
    "文字数",
    "何文字目",
    "CHR",
    "ASC",
    "文字挿入",
    "文字検索",
    "追加",
    "一行追加",
    "連結",
    "文字列連結",
    "文字列分解",
    "リフレイン",
    "出現回数",
    "MID",
    "文字抜出",
    "LEFT",
    "文字左部分",
    "RIGHT",
    "文字右部分",
    "区切",
    "文字列分割",
    "切取",
    "範囲切取",
    "文字削除",
    "文字始",
    "文字終",
    "出現",
    "置換",
    "単置換",
    "トリム",
    "空白除去",
    "右トリム",
    "左トリム",
    "末尾空白除去",
    "大文字変換",
    "小文字変換",
    "平仮名変換",
    "カタカナ変換",
    "英数全角変換",
    "英数半角変換",
    "英数記号全角変換",
    "英数記号半角変換",
    "カタカナ全角変換",
    "カタカナ半角変換",
    "全角変換",
    "半角変換",
    "全角カナ一覧",
    "全角カナ濁音一覧",
    "半角カナ一覧",
    "半角カナ濁音一覧",
    "通貨形式",
    "ゼロ埋",
    "空白埋",
    "かなか判定",
    "カタカナ判定",
    "数字判定",
    "数列判定",
    "配列結合",
    "配列只結合",
    "配列検索",
    "配列要素数",
    "要素数",
    "LEN",
    "配列挿入",
    "配列一括挿入",
    "配列ソート",
    "配列数値変換",
    "配列数値ソート",
    "配列カスタムソート",
    "配列逆順",
    "配列シャッフル",
    "配列削除",
    "配列切取",
    "配列取出",
    "配列ポップ",
    "配列プッシュ",
    "配列追加",
    "配列複製",
    "配列範囲コピー",
    "参照",
    "配列参照",
    "配列足",
    "配列最大値",
    "配列最小値",
    "配列合計",
    "配列入替",
    "配列連番作成",
    "配列要素作成",
    "配列関数適用",
    "配列マップ",
    "配列フィルタ",
    "表ソート",
    "表数値ソート",
    "表ピックアップ",
    "表完全一致ピックアップ",
    "表検索",
    "表列数",
    "表行数",
    "表行列交換",
    "表右回転",
    "表重複削除",
    "表列取得",
    "表列挿入",
    "表列削除",
    "表列合計",
    "表曖昧検索",
    "表正規表現ピックアップ",
    "元号データ",
    "今",
    "システム時間",
    "システム時間ミリ秒",
    "今日",
    "明日",
    "昨日",
    "今年",
    "来年",
    "去年",
    "今月",
    "来月",
    "先月",
    "曜日",
    "曜日番号取得",
    "UNIXTIME変換",
    "UNIX時間変換",
    "日時変換",
    "日時書式変換",
    "和暦変換",
    "年数差",
    "月数差",
    "日数差",
    "時間差",
    "分差",
    "秒差",
    "日時差",
    "時間加算",
    "日付加算",
    "日時加算",
    "時間ミリ秒取得",
    "URLエンコード",
    "URLデコード",
    "URLパラメータ解析",
    "BASE64エンコード",
    "BASE64デコード",
    "拡張子抽出",
    "拡張子変更",
    "終端パス追加",
    "終端パス除去",
    "終端パス削除",
    "ファイル名抽出",
    "パス抽出",
    "変数型確認",
    "TYPEOF",
    "文字列変換",
    "TOSTR",
    "整数変換",
    "TOINT",
    "実数変換",
    "TOFLOAT",
    "INT",
    "FLOAT",
    "NAN判定",
    "非数判定",
    "HEX",
    "進数変換",
    "二進",
    "二進表示",
    "RGB",
    "JSON変換",
    "JSON取得",
    "JSONエンコード",
    "JSONエンコード整形",
    "JSONデコード",
    "JSON_E",
    "JSON_ES",
    "JSON_D",
    "正規表現マッチ",
    "正規表現抽出",
    "抽出文字列",
    "正規表現置換",
    "正規表現区切",
    "辞書キー列挙",
    "辞書キー削除",
    "辞書キー存在",
    "ハッシュキー列挙",
    "ハッシュ内容列挙",
    "ハッシュキー削除",
    "ハッシュキー存在",
    "表示",
    "継続表示",
    "連続表示",
    "連続無改行表示",
    "表示ログ",
    "表示ログクリア",
    "言",
    "コンソール表示",
    "秒待",
    "秒待機",
    "秒逐次待機",
    "秒後",
    "秒毎",
    "秒タイマー開始時",
    "タイマー停止",
    "全タイマー停止",
    "CSV取得",
    "TSV取得",
    "表CSV変換",
    "CSV変換",
    "表TSV変換",
    "TSV変換",
    "CSVオプション設定",
    "TOML取得",
    "TOML変換",
    "SIN",
    "COS",
    "TAN",
    "ARCSIN",
    "ARCCOS",
    "ARCTAN",
    "ATAN2",
    "座標角度計算",
    "RAD2DEG",
    "DEG2RAD",
    "度変換",
    "ラジアン変換",
    "SIGN",
    "符号",
    "ABS",
    "絶対値",
    "EXP",
    "HYPOT",
    "斜辺",
    "LN",
    "LOG",
    "LOGN",
    "FRAC",
    "小数部分",
    "整数部分",
    "乱数",
    "乱数範囲",
    "SQRT",
    "平方根",
    "ROUND",
    "四捨五入",
    "小数点切上",
    "小数点切下",
    "小数点四捨五入",
    "CEIL",
    "切上",
    "FLOOR",
    "切捨",
    "そ",
    "動時",
    "成功時",
    "処理時",
    "失敗時",
    "終了時",
    "束",
    "開",
    "読",
    "バイナリ読",
    "保存",
    "SJISファイル読",
    "SJISファイル保存",
    "EUCファイル読",
    "EUCファイル保存",
    "起動待機",
    "コマンド実行",
    "コマンド実行待機",
    "起動",
    "コンソールクリア",
    "起動時",
    "ブラウザ起動",
    "エクスプローラー起動",
    "ファイル列挙",
    "全ファイル列挙",
    "存在",
    "フォルダ存在",
    "フォルダ作成",
    "ファイルコピーデフォルト動作",
    "ファイルコピー",
    "ファイル上書コピー",
    "ファイルコピー時",
    "ファイル移動",
    "ファイル上書移動",
    "ファイル処理時",
    "ファイル処理強制停止",
    "ファイル移動時",
    "ファイル削除",
    "ファイル削除時",
    "ファイル情報取得",
    "ファイルサイズ取得",
    "ファイル名抽出",
    "パス抽出",
    "絶対パス変換",
    "相対パス展開",
    "カレントディレクトリ取得",
    "カレントディレクトリ変更",
    "作業フォルダ取得",
    "作業フォルダ変更",
    "ホームディレクトリ取得",
    "デスクトップ",
    "マイドキュメント",
    "母艦パス",
    "母艦パス取得",
    "テンポラリフォルダ",
    "一時フォルダ作成",
    "環境変数取得",
    "環境変数一覧取得",
    "圧縮解凍ツールパス",
    "圧縮解凍ツールパス変更",
    "解凍",
    "解凍時",
    "圧縮",
    "圧縮時",
    "終",
    "プロセス終",
    "強制終了時",
    "終了",
    "OS取得",
    "OSアーキテクチャ取得",
    "コマンドライン",
    "ナデシコランタイム",
    "ナデシコランタイムパス",
    "標準入力取得時",
    "尋",
    "文字尋",
    "標準入力全取得",
    "ASSERT等",
    "自分IPアドレス取得",
    "自分IPV6アドレス取得",
    "AJAX送信時",
    "AJAX受信時",
    "GET送信時",
    "POST送信時",
    "POSTフォーム送信時",
    "AJAX失敗時",
    "AJAXオプション",
    "AJAXオプション設定",
    "AJAX保障送信",
    "HTTP保障取得",
    "GET保障送信",
    "POST保障送信",
    "POSTフォーム保障送信",
    "AJAX内容取得",
    "AJAX受信",
    "POSTデータ生成",
    "POST送信",
    "POSTフォーム送信",
    "AJAXテキスト取得",
    "AJAX_JSON取得",
    "AJAXバイナリ取得",
    "DISCORD送信",
    "DISCORDファイル送信",
    "LINE送信",
    "LINE画像送信",
    "文字コード変換サポート判定",
    "SJIS変換",
    "SJIS取得",
    "エンコーディング変換",
    "エンコーディング取得",
    "ハッシュ関数一覧取得",
    "ハッシュ値計算",
    "ランダムUUID生成",
    "ランダム配列生成",
    "HTTPメソッド",
    "GETデータ",
    "POSTデータ",
    "FILESデータ",
    "簡易HTTPサーバ起動時",
    "簡易HTTPサーバ静的パス指定",
    "簡易HTTPサーバ受信時",
    "簡易HTTPサーバ出力",
    "簡易HTTPサーバヘッダ出力",
    "簡易HTTPサーバ移動",
    "マークダウンHTML変換",
    "HTML整形",
    "元号データ",
    "今",
    "システム時間",
    "今日",
    "明日",
    "昨日",
    "今年",
    "来年",
    "去年",
    "今月",
    "来月",
    "先月",
    "曜日",
    "曜日番号取得",
    "UNIX時間変換",
    "UNIXTIME変換",
    "日時変換",
    "和暦変換",
    "年数差",
    "月数差",
    "日数差",
    "日時差",
    "時間差",
    "分差",
    "秒差",
    "時間加算",
    "日付加算",
    "日時加算",
    "ブラウザ名変換表",
    "対応ブラウザ一覧取得",
    "漢数字",
    "算用数字",
};

/// C風呼び出しの引数個数。standard-cnako.jsonの関数定義から生成。
pub const BuiltinArity = struct {
    name: []const u8,
    count: usize,
    is_variable: bool,
};

pub const arities = [_]BuiltinArity{
    .{ .name = "空配列", .count = 0, .is_variable = false },
    .{ .name = "空辞書", .count = 0, .is_variable = false },
    .{ .name = "空ハッシュ", .count = 0, .is_variable = false },
    .{ .name = "空オブジェクト", .count = 0, .is_variable = false },
    .{ .name = "真偽判定", .count = 1, .is_variable = false },
    .{ .name = "ください", .count = 0, .is_variable = false },
    .{ .name = "お願", .count = 0, .is_variable = false },
    .{ .name = "です", .count = 0, .is_variable = false },
    .{ .name = "拝啓", .count = 0, .is_variable = false },
    .{ .name = "敬具", .count = 0, .is_variable = false },
    .{ .name = "礼節レベル取得", .count = 0, .is_variable = false },
    .{ .name = "JS実行", .count = 1, .is_variable = false },
    .{ .name = "JSオブジェクト取得", .count = 1, .is_variable = false },
    .{ .name = "JS関数実行", .count = 2, .is_variable = false },
    .{ .name = "ASYNC", .count = 0, .is_variable = false },
    .{ .name = "AWAIT実行", .count = 2, .is_variable = false },
    .{ .name = "JSメソッド実行", .count = 3, .is_variable = false },
    .{ .name = "ナデシコ", .count = 1, .is_variable = false },
    .{ .name = "ナデシコ続", .count = 1, .is_variable = false },
    .{ .name = "実行", .count = 1, .is_variable = false },
    .{ .name = "実行時間計測", .count = 1, .is_variable = false },
    .{ .name = "終", .count = 0, .is_variable = false },
    .{ .name = "デバッグ表示", .count = 1, .is_variable = false },
    .{ .name = "ハテナ関数設定", .count = 1, .is_variable = false },
    .{ .name = "ハテナ関数実行", .count = 1, .is_variable = false },
    .{ .name = "エラー発生", .count = 1, .is_variable = false },
    .{ .name = "__DEBUG", .count = 0, .is_variable = false },
    .{ .name = "__DEBUG_BP_WAIT", .count = 1, .is_variable = false },
    .{ .name = "グローバル関数一覧取得", .count = 0, .is_variable = false },
    .{ .name = "システム関数一覧取得", .count = 0, .is_variable = false },
    .{ .name = "システム関数存在", .count = 1, .is_variable = false },
    .{ .name = "プラグイン一覧取得", .count = 0, .is_variable = false },
    .{ .name = "モジュール一覧取得", .count = 0, .is_variable = false },
    .{ .name = "助詞一覧取得", .count = 0, .is_variable = false },
    .{ .name = "予約語一覧取得", .count = 0, .is_variable = false },
    .{ .name = "プラグイン名設定", .count = 1, .is_variable = false },
    .{ .name = "名前空間設定", .count = 1, .is_variable = false },
    .{ .name = "名前空間ポップ", .count = 0, .is_variable = false },
    .{ .name = "足", .count = 2, .is_variable = false },
    .{ .name = "合計", .count = 1, .is_variable = true },
    .{ .name = "引", .count = 2, .is_variable = false },
    .{ .name = "掛", .count = 2, .is_variable = false },
    .{ .name = "倍", .count = 2, .is_variable = false },
    .{ .name = "割", .count = 2, .is_variable = false },
    .{ .name = "割余", .count = 2, .is_variable = false },
    .{ .name = "偶数", .count = 1, .is_variable = false },
    .{ .name = "奇数", .count = 1, .is_variable = false },
    .{ .name = "二乗", .count = 1, .is_variable = false },
    .{ .name = "べき乗", .count = 2, .is_variable = false },
    .{ .name = "以上", .count = 2, .is_variable = false },
    .{ .name = "以下", .count = 2, .is_variable = false },
    .{ .name = "未満", .count = 2, .is_variable = false },
    .{ .name = "超", .count = 2, .is_variable = false },
    .{ .name = "等", .count = 2, .is_variable = false },
    .{ .name = "等無", .count = 2, .is_variable = false },
    .{ .name = "一致", .count = 2, .is_variable = false },
    .{ .name = "不一致", .count = 2, .is_variable = false },
    .{ .name = "範囲内", .count = 3, .is_variable = false },
    .{ .name = "範囲", .count = 2, .is_variable = false },
    .{ .name = "連続加算", .count = 2, .is_variable = true },
    .{ .name = "MAX", .count = 2, .is_variable = true },
    .{ .name = "最大値", .count = 2, .is_variable = true },
    .{ .name = "MIN", .count = 2, .is_variable = true },
    .{ .name = "最小値", .count = 2, .is_variable = true },
    .{ .name = "CLAMP", .count = 3, .is_variable = false },
    .{ .name = "論理OR", .count = 2, .is_variable = false },
    .{ .name = "論理AND", .count = 2, .is_variable = false },
    .{ .name = "論理NOT", .count = 1, .is_variable = false },
    .{ .name = "OR", .count = 2, .is_variable = false },
    .{ .name = "AND", .count = 2, .is_variable = false },
    .{ .name = "XOR", .count = 2, .is_variable = false },
    .{ .name = "NOT", .count = 1, .is_variable = false },
    .{ .name = "SHIFT_L", .count = 2, .is_variable = false },
    .{ .name = "SHIFT_R", .count = 2, .is_variable = false },
    .{ .name = "SHIFT_UR", .count = 2, .is_variable = false },
    .{ .name = "文字数", .count = 1, .is_variable = false },
    .{ .name = "何文字目", .count = 2, .is_variable = false },
    .{ .name = "CHR", .count = 1, .is_variable = false },
    .{ .name = "ASC", .count = 1, .is_variable = false },
    .{ .name = "文字挿入", .count = 3, .is_variable = false },
    .{ .name = "文字検索", .count = 3, .is_variable = false },
    .{ .name = "追加", .count = 2, .is_variable = false },
    .{ .name = "一行追加", .count = 2, .is_variable = false },
    .{ .name = "連結", .count = 1, .is_variable = true },
    .{ .name = "文字列連結", .count = 1, .is_variable = true },
    .{ .name = "文字列分解", .count = 1, .is_variable = false },
    .{ .name = "リフレイン", .count = 2, .is_variable = false },
    .{ .name = "出現回数", .count = 2, .is_variable = false },
    .{ .name = "MID", .count = 3, .is_variable = false },
    .{ .name = "文字抜出", .count = 3, .is_variable = false },
    .{ .name = "LEFT", .count = 2, .is_variable = false },
    .{ .name = "文字左部分", .count = 2, .is_variable = false },
    .{ .name = "RIGHT", .count = 2, .is_variable = false },
    .{ .name = "文字右部分", .count = 2, .is_variable = false },
    .{ .name = "区切", .count = 2, .is_variable = false },
    .{ .name = "文字列分割", .count = 2, .is_variable = false },
    .{ .name = "切取", .count = 2, .is_variable = false },
    .{ .name = "範囲切取", .count = 3, .is_variable = false },
    .{ .name = "文字削除", .count = 3, .is_variable = false },
    .{ .name = "文字始", .count = 2, .is_variable = false },
    .{ .name = "文字終", .count = 2, .is_variable = false },
    .{ .name = "出現", .count = 2, .is_variable = false },
    .{ .name = "置換", .count = 3, .is_variable = false },
    .{ .name = "単置換", .count = 3, .is_variable = false },
    .{ .name = "トリム", .count = 1, .is_variable = false },
    .{ .name = "空白除去", .count = 1, .is_variable = false },
    .{ .name = "右トリム", .count = 1, .is_variable = false },
    .{ .name = "左トリム", .count = 1, .is_variable = false },
    .{ .name = "末尾空白除去", .count = 1, .is_variable = false },
    .{ .name = "大文字変換", .count = 1, .is_variable = false },
    .{ .name = "小文字変換", .count = 1, .is_variable = false },
    .{ .name = "平仮名変換", .count = 1, .is_variable = false },
    .{ .name = "カタカナ変換", .count = 1, .is_variable = false },
    .{ .name = "英数全角変換", .count = 1, .is_variable = false },
    .{ .name = "英数半角変換", .count = 1, .is_variable = false },
    .{ .name = "英数記号全角変換", .count = 1, .is_variable = false },
    .{ .name = "英数記号半角変換", .count = 1, .is_variable = false },
    .{ .name = "カタカナ全角変換", .count = 1, .is_variable = false },
    .{ .name = "カタカナ半角変換", .count = 1, .is_variable = false },
    .{ .name = "全角変換", .count = 1, .is_variable = false },
    .{ .name = "半角変換", .count = 1, .is_variable = false },
    .{ .name = "通貨形式", .count = 1, .is_variable = false },
    .{ .name = "ゼロ埋", .count = 2, .is_variable = false },
    .{ .name = "空白埋", .count = 2, .is_variable = false },
    .{ .name = "かなか判定", .count = 1, .is_variable = false },
    .{ .name = "カタカナ判定", .count = 1, .is_variable = false },
    .{ .name = "数字判定", .count = 1, .is_variable = false },
    .{ .name = "数列判定", .count = 1, .is_variable = false },
    .{ .name = "配列結合", .count = 2, .is_variable = false },
    .{ .name = "配列只結合", .count = 1, .is_variable = false },
    .{ .name = "配列検索", .count = 2, .is_variable = false },
    .{ .name = "配列要素数", .count = 1, .is_variable = false },
    .{ .name = "要素数", .count = 1, .is_variable = false },
    .{ .name = "LEN", .count = 1, .is_variable = false },
    .{ .name = "配列挿入", .count = 3, .is_variable = false },
    .{ .name = "配列一括挿入", .count = 3, .is_variable = false },
    .{ .name = "配列ソート", .count = 1, .is_variable = false },
    .{ .name = "配列数値変換", .count = 1, .is_variable = false },
    .{ .name = "配列数値ソート", .count = 1, .is_variable = false },
    .{ .name = "配列カスタムソート", .count = 2, .is_variable = false },
    .{ .name = "配列逆順", .count = 1, .is_variable = false },
    .{ .name = "配列シャッフル", .count = 1, .is_variable = false },
    .{ .name = "配列削除", .count = 2, .is_variable = false },
    .{ .name = "配列切取", .count = 2, .is_variable = false },
    .{ .name = "配列取出", .count = 3, .is_variable = false },
    .{ .name = "配列ポップ", .count = 1, .is_variable = false },
    .{ .name = "配列プッシュ", .count = 2, .is_variable = false },
    .{ .name = "配列追加", .count = 2, .is_variable = false },
    .{ .name = "配列複製", .count = 1, .is_variable = false },
    .{ .name = "配列範囲コピー", .count = 2, .is_variable = false },
    .{ .name = "参照", .count = 2, .is_variable = false },
    .{ .name = "配列参照", .count = 2, .is_variable = false },
    .{ .name = "配列足", .count = 2, .is_variable = false },
    .{ .name = "配列最大値", .count = 1, .is_variable = false },
    .{ .name = "配列最小値", .count = 1, .is_variable = false },
    .{ .name = "配列合計", .count = 1, .is_variable = false },
    .{ .name = "配列入替", .count = 3, .is_variable = false },
    .{ .name = "配列連番作成", .count = 2, .is_variable = false },
    .{ .name = "配列要素作成", .count = 2, .is_variable = false },
    .{ .name = "配列関数適用", .count = 2, .is_variable = false },
    .{ .name = "配列マップ", .count = 2, .is_variable = false },
    .{ .name = "配列フィルタ", .count = 2, .is_variable = false },
    .{ .name = "表ソート", .count = 2, .is_variable = false },
    .{ .name = "表数値ソート", .count = 2, .is_variable = false },
    .{ .name = "表ピックアップ", .count = 3, .is_variable = false },
    .{ .name = "表完全一致ピックアップ", .count = 3, .is_variable = false },
    .{ .name = "表検索", .count = 4, .is_variable = false },
    .{ .name = "表列数", .count = 1, .is_variable = false },
    .{ .name = "表行数", .count = 1, .is_variable = false },
    .{ .name = "表行列交換", .count = 1, .is_variable = false },
    .{ .name = "表右回転", .count = 1, .is_variable = false },
    .{ .name = "表重複削除", .count = 2, .is_variable = false },
    .{ .name = "表列取得", .count = 2, .is_variable = false },
    .{ .name = "表列挿入", .count = 3, .is_variable = false },
    .{ .name = "表列削除", .count = 2, .is_variable = false },
    .{ .name = "表列合計", .count = 2, .is_variable = false },
    .{ .name = "表曖昧検索", .count = 4, .is_variable = false },
    .{ .name = "表正規表現ピックアップ", .count = 3, .is_variable = false },
    .{ .name = "今", .count = 0, .is_variable = false },
    .{ .name = "システム時間", .count = 0, .is_variable = false },
    .{ .name = "システム時間ミリ秒", .count = 0, .is_variable = false },
    .{ .name = "今日", .count = 0, .is_variable = false },
    .{ .name = "明日", .count = 0, .is_variable = false },
    .{ .name = "昨日", .count = 0, .is_variable = false },
    .{ .name = "今年", .count = 0, .is_variable = false },
    .{ .name = "来年", .count = 0, .is_variable = false },
    .{ .name = "去年", .count = 0, .is_variable = false },
    .{ .name = "今月", .count = 0, .is_variable = false },
    .{ .name = "来月", .count = 0, .is_variable = false },
    .{ .name = "先月", .count = 0, .is_variable = false },
    .{ .name = "曜日", .count = 1, .is_variable = false },
    .{ .name = "曜日番号取得", .count = 1, .is_variable = false },
    .{ .name = "UNIXTIME変換", .count = 1, .is_variable = false },
    .{ .name = "UNIX時間変換", .count = 1, .is_variable = false },
    .{ .name = "日時変換", .count = 1, .is_variable = false },
    .{ .name = "日時書式変換", .count = 2, .is_variable = false },
    .{ .name = "和暦変換", .count = 1, .is_variable = false },
    .{ .name = "年数差", .count = 2, .is_variable = false },
    .{ .name = "月数差", .count = 2, .is_variable = false },
    .{ .name = "日数差", .count = 2, .is_variable = false },
    .{ .name = "時間差", .count = 2, .is_variable = false },
    .{ .name = "分差", .count = 2, .is_variable = false },
    .{ .name = "秒差", .count = 2, .is_variable = false },
    .{ .name = "日時差", .count = 3, .is_variable = false },
    .{ .name = "時間加算", .count = 2, .is_variable = false },
    .{ .name = "日付加算", .count = 2, .is_variable = false },
    .{ .name = "日時加算", .count = 2, .is_variable = false },
    .{ .name = "時間ミリ秒取得", .count = 0, .is_variable = false },
    .{ .name = "URLエンコード", .count = 1, .is_variable = false },
    .{ .name = "URLデコード", .count = 1, .is_variable = false },
    .{ .name = "URLパラメータ解析", .count = 1, .is_variable = false },
    .{ .name = "BASE64エンコード", .count = 1, .is_variable = false },
    .{ .name = "BASE64デコード", .count = 1, .is_variable = false },
    .{ .name = "拡張子抽出", .count = 1, .is_variable = false },
    .{ .name = "拡張子変更", .count = 2, .is_variable = false },
    .{ .name = "終端パス追加", .count = 1, .is_variable = false },
    .{ .name = "終端パス除去", .count = 1, .is_variable = false },
    .{ .name = "終端パス削除", .count = 1, .is_variable = false },
    .{ .name = "ファイル名抽出", .count = 1, .is_variable = false },
    .{ .name = "パス抽出", .count = 1, .is_variable = false },
    .{ .name = "変数型確認", .count = 1, .is_variable = false },
    .{ .name = "TYPEOF", .count = 1, .is_variable = false },
    .{ .name = "文字列変換", .count = 1, .is_variable = false },
    .{ .name = "TOSTR", .count = 1, .is_variable = false },
    .{ .name = "整数変換", .count = 1, .is_variable = false },
    .{ .name = "TOINT", .count = 1, .is_variable = false },
    .{ .name = "実数変換", .count = 1, .is_variable = false },
    .{ .name = "TOFLOAT", .count = 1, .is_variable = false },
    .{ .name = "INT", .count = 1, .is_variable = false },
    .{ .name = "FLOAT", .count = 1, .is_variable = false },
    .{ .name = "NAN判定", .count = 1, .is_variable = false },
    .{ .name = "非数判定", .count = 1, .is_variable = false },
    .{ .name = "HEX", .count = 1, .is_variable = false },
    .{ .name = "進数変換", .count = 2, .is_variable = false },
    .{ .name = "二進", .count = 1, .is_variable = false },
    .{ .name = "二進表示", .count = 1, .is_variable = false },
    .{ .name = "RGB", .count = 3, .is_variable = false },
    .{ .name = "JSON変換", .count = 1, .is_variable = false },
    .{ .name = "JSON取得", .count = 1, .is_variable = false },
    .{ .name = "JSONエンコード", .count = 1, .is_variable = false },
    .{ .name = "JSONエンコード整形", .count = 1, .is_variable = false },
    .{ .name = "JSONデコード", .count = 1, .is_variable = false },
    .{ .name = "JSON_E", .count = 1, .is_variable = false },
    .{ .name = "JSON_ES", .count = 1, .is_variable = false },
    .{ .name = "JSON_D", .count = 1, .is_variable = false },
    .{ .name = "正規表現マッチ", .count = 2, .is_variable = false },
    .{ .name = "正規表現抽出", .count = 2, .is_variable = false },
    .{ .name = "正規表現置換", .count = 3, .is_variable = false },
    .{ .name = "正規表現区切", .count = 2, .is_variable = false },
    .{ .name = "辞書キー列挙", .count = 1, .is_variable = false },
    .{ .name = "辞書キー削除", .count = 2, .is_variable = false },
    .{ .name = "辞書キー存在", .count = 2, .is_variable = false },
    .{ .name = "ハッシュキー列挙", .count = 1, .is_variable = false },
    .{ .name = "ハッシュ内容列挙", .count = 1, .is_variable = false },
    .{ .name = "ハッシュキー削除", .count = 2, .is_variable = false },
    .{ .name = "ハッシュキー存在", .count = 2, .is_variable = false },
    .{ .name = "表示", .count = 1, .is_variable = false },
    .{ .name = "継続表示", .count = 1, .is_variable = false },
    .{ .name = "連続表示", .count = 1, .is_variable = true },
    .{ .name = "連続無改行表示", .count = 1, .is_variable = true },
    .{ .name = "表示ログクリア", .count = 0, .is_variable = false },
    .{ .name = "言", .count = 1, .is_variable = false },
    .{ .name = "コンソール表示", .count = 1, .is_variable = false },
    .{ .name = "秒待", .count = 1, .is_variable = false },
    .{ .name = "秒待機", .count = 1, .is_variable = false },
    .{ .name = "秒逐次待機", .count = 1, .is_variable = false },
    .{ .name = "秒後", .count = 2, .is_variable = false },
    .{ .name = "秒毎", .count = 2, .is_variable = false },
    .{ .name = "秒タイマー開始時", .count = 2, .is_variable = false },
    .{ .name = "タイマー停止", .count = 1, .is_variable = false },
    .{ .name = "全タイマー停止", .count = 0, .is_variable = false },
    .{ .name = "CSV取得", .count = 1, .is_variable = false },
    .{ .name = "TSV取得", .count = 1, .is_variable = false },
    .{ .name = "表CSV変換", .count = 1, .is_variable = false },
    .{ .name = "CSV変換", .count = 1, .is_variable = false },
    .{ .name = "表TSV変換", .count = 1, .is_variable = false },
    .{ .name = "TSV変換", .count = 1, .is_variable = false },
    .{ .name = "CSVオプション設定", .count = 1, .is_variable = false },
    .{ .name = "TOML取得", .count = 1, .is_variable = false },
    .{ .name = "TOML変換", .count = 1, .is_variable = false },
    .{ .name = "SIN", .count = 1, .is_variable = false },
    .{ .name = "COS", .count = 1, .is_variable = false },
    .{ .name = "TAN", .count = 1, .is_variable = false },
    .{ .name = "ARCSIN", .count = 1, .is_variable = false },
    .{ .name = "ARCCOS", .count = 1, .is_variable = false },
    .{ .name = "ARCTAN", .count = 1, .is_variable = false },
    .{ .name = "ATAN2", .count = 2, .is_variable = false },
    .{ .name = "座標角度計算", .count = 1, .is_variable = false },
    .{ .name = "RAD2DEG", .count = 1, .is_variable = false },
    .{ .name = "DEG2RAD", .count = 1, .is_variable = false },
    .{ .name = "度変換", .count = 1, .is_variable = false },
    .{ .name = "ラジアン変換", .count = 1, .is_variable = false },
    .{ .name = "SIGN", .count = 1, .is_variable = false },
    .{ .name = "符号", .count = 1, .is_variable = false },
    .{ .name = "ABS", .count = 1, .is_variable = false },
    .{ .name = "絶対値", .count = 1, .is_variable = false },
    .{ .name = "EXP", .count = 1, .is_variable = false },
    .{ .name = "HYPOT", .count = 2, .is_variable = false },
    .{ .name = "斜辺", .count = 2, .is_variable = false },
    .{ .name = "LN", .count = 1, .is_variable = false },
    .{ .name = "LOG", .count = 1, .is_variable = false },
    .{ .name = "LOGN", .count = 2, .is_variable = false },
    .{ .name = "FRAC", .count = 1, .is_variable = false },
    .{ .name = "小数部分", .count = 1, .is_variable = false },
    .{ .name = "整数部分", .count = 1, .is_variable = false },
    .{ .name = "乱数", .count = 1, .is_variable = false },
    .{ .name = "乱数範囲", .count = 2, .is_variable = false },
    .{ .name = "SQRT", .count = 1, .is_variable = false },
    .{ .name = "平方根", .count = 1, .is_variable = false },
    .{ .name = "ROUND", .count = 1, .is_variable = false },
    .{ .name = "四捨五入", .count = 1, .is_variable = false },
    .{ .name = "小数点切上", .count = 2, .is_variable = false },
    .{ .name = "小数点切下", .count = 2, .is_variable = false },
    .{ .name = "小数点四捨五入", .count = 2, .is_variable = false },
    .{ .name = "CEIL", .count = 1, .is_variable = false },
    .{ .name = "切上", .count = 1, .is_variable = false },
    .{ .name = "FLOOR", .count = 1, .is_variable = false },
    .{ .name = "切捨", .count = 1, .is_variable = false },
    .{ .name = "動時", .count = 1, .is_variable = false },
    .{ .name = "成功時", .count = 2, .is_variable = false },
    .{ .name = "処理時", .count = 2, .is_variable = false },
    .{ .name = "失敗時", .count = 2, .is_variable = false },
    .{ .name = "終了時", .count = 2, .is_variable = false },
    .{ .name = "束", .count = 1, .is_variable = true },
    .{ .name = "開", .count = 1, .is_variable = false },
    .{ .name = "読", .count = 1, .is_variable = false },
    .{ .name = "バイナリ読", .count = 1, .is_variable = false },
    .{ .name = "保存", .count = 2, .is_variable = false },
    .{ .name = "SJISファイル読", .count = 1, .is_variable = false },
    .{ .name = "SJISファイル保存", .count = 2, .is_variable = false },
    .{ .name = "EUCファイル読", .count = 1, .is_variable = false },
    .{ .name = "EUCファイル保存", .count = 2, .is_variable = false },
    .{ .name = "起動待機", .count = 1, .is_variable = false },
    .{ .name = "コマンド実行", .count = 1, .is_variable = false },
    .{ .name = "コマンド実行待機", .count = 1, .is_variable = false },
    .{ .name = "起動", .count = 1, .is_variable = false },
    .{ .name = "コンソールクリア", .count = 0, .is_variable = false },
    .{ .name = "起動時", .count = 2, .is_variable = false },
    .{ .name = "ブラウザ起動", .count = 1, .is_variable = false },
    .{ .name = "エクスプローラー起動", .count = 1, .is_variable = false },
    .{ .name = "ファイル列挙", .count = 1, .is_variable = false },
    .{ .name = "全ファイル列挙", .count = 1, .is_variable = false },
    .{ .name = "存在", .count = 1, .is_variable = false },
    .{ .name = "フォルダ存在", .count = 1, .is_variable = false },
    .{ .name = "フォルダ作成", .count = 1, .is_variable = false },
    .{ .name = "ファイルコピー", .count = 2, .is_variable = false },
    .{ .name = "ファイル上書コピー", .count = 2, .is_variable = false },
    .{ .name = "ファイルコピー時", .count = 3, .is_variable = false },
    .{ .name = "ファイル移動", .count = 2, .is_variable = false },
    .{ .name = "ファイル上書移動", .count = 2, .is_variable = false },
    .{ .name = "ファイル処理時", .count = 1, .is_variable = false },
    .{ .name = "ファイル処理強制停止", .count = 0, .is_variable = false },
    .{ .name = "ファイル移動時", .count = 3, .is_variable = false },
    .{ .name = "ファイル削除", .count = 1, .is_variable = false },
    .{ .name = "ファイル削除時", .count = 2, .is_variable = false },
    .{ .name = "ファイル情報取得", .count = 1, .is_variable = false },
    .{ .name = "ファイルサイズ取得", .count = 1, .is_variable = false },
    .{ .name = "絶対パス変換", .count = 1, .is_variable = false },
    .{ .name = "相対パス展開", .count = 2, .is_variable = false },
    .{ .name = "カレントディレクトリ取得", .count = 0, .is_variable = false },
    .{ .name = "カレントディレクトリ変更", .count = 1, .is_variable = false },
    .{ .name = "作業フォルダ取得", .count = 0, .is_variable = false },
    .{ .name = "作業フォルダ変更", .count = 1, .is_variable = false },
    .{ .name = "ホームディレクトリ取得", .count = 0, .is_variable = false },
    .{ .name = "デスクトップ", .count = 0, .is_variable = false },
    .{ .name = "マイドキュメント", .count = 0, .is_variable = false },
    .{ .name = "母艦パス取得", .count = 0, .is_variable = false },
    .{ .name = "テンポラリフォルダ", .count = 0, .is_variable = false },
    .{ .name = "一時フォルダ作成", .count = 1, .is_variable = false },
    .{ .name = "環境変数取得", .count = 1, .is_variable = false },
    .{ .name = "環境変数一覧取得", .count = 0, .is_variable = false },
    .{ .name = "圧縮解凍ツールパス変更", .count = 1, .is_variable = false },
    .{ .name = "解凍", .count = 2, .is_variable = false },
    .{ .name = "解凍時", .count = 3, .is_variable = false },
    .{ .name = "圧縮", .count = 2, .is_variable = false },
    .{ .name = "圧縮時", .count = 3, .is_variable = false },
    .{ .name = "プロセス終", .count = 1, .is_variable = false },
    .{ .name = "強制終了時", .count = 1, .is_variable = false },
    .{ .name = "終了", .count = 0, .is_variable = false },
    .{ .name = "OS取得", .count = 0, .is_variable = false },
    .{ .name = "OSアーキテクチャ取得", .count = 0, .is_variable = false },
    .{ .name = "標準入力取得時", .count = 2, .is_variable = false },
    .{ .name = "尋", .count = 1, .is_variable = false },
    .{ .name = "文字尋", .count = 1, .is_variable = false },
    .{ .name = "標準入力全取得", .count = 0, .is_variable = false },
    .{ .name = "ASSERT等", .count = 2, .is_variable = false },
    .{ .name = "自分IPアドレス取得", .count = 0, .is_variable = false },
    .{ .name = "自分IPV6アドレス取得", .count = 0, .is_variable = false },
    .{ .name = "AJAX送信時", .count = 2, .is_variable = false },
    .{ .name = "AJAX受信時", .count = 2, .is_variable = false },
    .{ .name = "GET送信時", .count = 2, .is_variable = false },
    .{ .name = "POST送信時", .count = 3, .is_variable = false },
    .{ .name = "POSTフォーム送信時", .count = 3, .is_variable = false },
    .{ .name = "AJAX失敗時", .count = 1, .is_variable = false },
    .{ .name = "AJAXオプション設定", .count = 1, .is_variable = false },
    .{ .name = "AJAX保障送信", .count = 1, .is_variable = false },
    .{ .name = "HTTP保障取得", .count = 1, .is_variable = false },
    .{ .name = "GET保障送信", .count = 1, .is_variable = false },
    .{ .name = "POST保障送信", .count = 2, .is_variable = false },
    .{ .name = "POSTフォーム保障送信", .count = 2, .is_variable = false },
    .{ .name = "AJAX内容取得", .count = 2, .is_variable = false },
    .{ .name = "AJAX受信", .count = 1, .is_variable = false },
    .{ .name = "POSTデータ生成", .count = 1, .is_variable = false },
    .{ .name = "POST送信", .count = 2, .is_variable = false },
    .{ .name = "POSTフォーム送信", .count = 2, .is_variable = false },
    .{ .name = "AJAXテキスト取得", .count = 1, .is_variable = false },
    .{ .name = "AJAX_JSON取得", .count = 1, .is_variable = false },
    .{ .name = "AJAXバイナリ取得", .count = 1, .is_variable = false },
    .{ .name = "DISCORD送信", .count = 2, .is_variable = false },
    .{ .name = "DISCORDファイル送信", .count = 3, .is_variable = false },
    .{ .name = "LINE送信", .count = 2, .is_variable = false },
    .{ .name = "LINE画像送信", .count = 3, .is_variable = false },
    .{ .name = "文字コード変換サポート判定", .count = 1, .is_variable = false },
    .{ .name = "SJIS変換", .count = 1, .is_variable = false },
    .{ .name = "SJIS取得", .count = 1, .is_variable = false },
    .{ .name = "エンコーディング変換", .count = 2, .is_variable = false },
    .{ .name = "エンコーディング取得", .count = 2, .is_variable = false },
    .{ .name = "ハッシュ関数一覧取得", .count = 0, .is_variable = false },
    .{ .name = "ハッシュ値計算", .count = 3, .is_variable = false },
    .{ .name = "ランダムUUID生成", .count = 0, .is_variable = false },
    .{ .name = "ランダム配列生成", .count = 1, .is_variable = false },
    .{ .name = "簡易HTTPサーバ起動時", .count = 2, .is_variable = false },
    .{ .name = "簡易HTTPサーバ静的パス指定", .count = 2, .is_variable = false },
    .{ .name = "簡易HTTPサーバ受信時", .count = 2, .is_variable = false },
    .{ .name = "簡易HTTPサーバ出力", .count = 1, .is_variable = false },
    .{ .name = "簡易HTTPサーバヘッダ出力", .count = 2, .is_variable = false },
    .{ .name = "簡易HTTPサーバ移動", .count = 1, .is_variable = false },
    .{ .name = "マークダウンHTML変換", .count = 1, .is_variable = false },
    .{ .name = "HTML整形", .count = 1, .is_variable = false },
    .{ .name = "対応ブラウザ一覧取得", .count = 0, .is_variable = false },
    .{ .name = "漢数字", .count = 1, .is_variable = false },
    .{ .name = "算用数字", .count = 1, .is_variable = false },
};

pub fn findArity(name: []const u8) ?BuiltinArity {
    for (arities) |entry| if (std.mem.eql(u8, entry.name, name)) return entry;
    return null;
}

/// 公式cnako3が既定で読み込む7プラグインの公開システム変数名。
pub const default_names = [_][]const u8{
    "ナデシコバージョン",
    "ナデシコ言語バージョン",
    "ナデシコエンジン",
    "ナデシコ種類",
    "はい",
    "いいえ",
    "真",
    "偽",
    "永遠",
    "オン",
    "オフ",
    "改行",
    "タブ",
    "カッコ",
    "カッコ閉",
    "波カッコ",
    "波カッコ閉",
    "OK",
    "NG",
    "キャンセル",
    "TRUE",
    "FALSE",
    "true",
    "false",
    "PI",
    "空",
    "NULL",
    "undefined",
    "未定義",
    "エラーメッセージ",
    "対象",
    "対象キー",
    "回数",
    "CR",
    "LF",
    "非数",
    "無限大",
    "戻値無",
    "戻値有",
    "空配列",
    "空辞書",
    "空ハッシュ",
    "空オブジェクト",
    "真偽判定",
    "ください",
    "お願",
    "です",
    "拝啓",
    "敬具",
    "礼節レベル取得",
    "JS実行",
    "JSオブジェクト取得",
    "JS関数実行",
    "ASYNC",
    "AWAIT実行",
    "JSメソッド実行",
    "ナデシコ",
    "ナデシコ続",
    "実行",
    "実行時間計測",
    "終",
    "デバッグ表示",
    "ハテナ関数設定",
    "ハテナ関数実行",
    "エラー発生",
    "グローバル関数一覧取得",
    "システム関数一覧取得",
    "システム関数存在",
    "プラグイン一覧取得",
    "モジュール一覧取得",
    "助詞一覧取得",
    "予約語一覧取得",
    "プラグイン名",
    "プラグイン名設定",
    "名前空間",
    "名前空間設定",
    "名前空間ポップ",
    "足",
    "合計",
    "引",
    "掛",
    "倍",
    "割",
    "割余",
    "偶数",
    "奇数",
    "二乗",
    "べき乗",
    "以上",
    "以下",
    "未満",
    "超",
    "等",
    "等無",
    "一致",
    "不一致",
    "範囲内",
    "範囲",
    "連続加算",
    "MAX",
    "最大値",
    "MIN",
    "最小値",
    "CLAMP",
    "論理OR",
    "論理AND",
    "論理NOT",
    "OR",
    "AND",
    "XOR",
    "NOT",
    "SHIFT_L",
    "SHIFT_R",
    "SHIFT_UR",
    "文字数",
    "何文字目",
    "CHR",
    "ASC",
    "文字挿入",
    "文字検索",
    "追加",
    "一行追加",
    "連結",
    "文字列連結",
    "文字列分解",
    "リフレイン",
    "出現回数",
    "MID",
    "文字抜出",
    "LEFT",
    "文字左部分",
    "RIGHT",
    "文字右部分",
    "区切",
    "文字列分割",
    "切取",
    "範囲切取",
    "文字削除",
    "文字始",
    "文字終",
    "出現",
    "置換",
    "単置換",
    "トリム",
    "空白除去",
    "右トリム",
    "左トリム",
    "末尾空白除去",
    "大文字変換",
    "小文字変換",
    "平仮名変換",
    "カタカナ変換",
    "英数全角変換",
    "英数半角変換",
    "英数記号全角変換",
    "英数記号半角変換",
    "カタカナ全角変換",
    "カタカナ半角変換",
    "全角変換",
    "半角変換",
    "全角カナ一覧",
    "全角カナ濁音一覧",
    "半角カナ一覧",
    "半角カナ濁音一覧",
    "通貨形式",
    "ゼロ埋",
    "空白埋",
    "かなか判定",
    "カタカナ判定",
    "数字判定",
    "数列判定",
    "配列結合",
    "配列只結合",
    "配列検索",
    "配列要素数",
    "要素数",
    "LEN",
    "配列挿入",
    "配列一括挿入",
    "配列ソート",
    "配列数値変換",
    "配列数値ソート",
    "配列カスタムソート",
    "配列逆順",
    "配列シャッフル",
    "配列削除",
    "配列切取",
    "配列取出",
    "配列ポップ",
    "配列プッシュ",
    "配列追加",
    "配列複製",
    "配列範囲コピー",
    "参照",
    "配列参照",
    "配列足",
    "配列最大値",
    "配列最小値",
    "配列合計",
    "配列入替",
    "配列連番作成",
    "配列要素作成",
    "配列関数適用",
    "配列マップ",
    "配列フィルタ",
    "表ソート",
    "表数値ソート",
    "表ピックアップ",
    "表完全一致ピックアップ",
    "表検索",
    "表列数",
    "表行数",
    "表行列交換",
    "表右回転",
    "表重複削除",
    "表列取得",
    "表列挿入",
    "表列削除",
    "表列合計",
    "表曖昧検索",
    "表正規表現ピックアップ",
    "元号データ",
    "今",
    "システム時間",
    "システム時間ミリ秒",
    "今日",
    "明日",
    "昨日",
    "今年",
    "来年",
    "去年",
    "今月",
    "来月",
    "先月",
    "曜日",
    "曜日番号取得",
    "UNIXTIME変換",
    "UNIX時間変換",
    "日時変換",
    "日時書式変換",
    "和暦変換",
    "年数差",
    "月数差",
    "日数差",
    "時間差",
    "分差",
    "秒差",
    "日時差",
    "時間加算",
    "日付加算",
    "日時加算",
    "時間ミリ秒取得",
    "URLエンコード",
    "URLデコード",
    "URLパラメータ解析",
    "BASE64エンコード",
    "BASE64デコード",
    "拡張子抽出",
    "拡張子変更",
    "終端パス追加",
    "終端パス除去",
    "終端パス削除",
    "ファイル名抽出",
    "パス抽出",
    "変数型確認",
    "TYPEOF",
    "文字列変換",
    "TOSTR",
    "整数変換",
    "TOINT",
    "実数変換",
    "TOFLOAT",
    "INT",
    "FLOAT",
    "NAN判定",
    "非数判定",
    "HEX",
    "進数変換",
    "二進",
    "二進表示",
    "RGB",
    "JSON変換",
    "JSON取得",
    "JSONエンコード",
    "JSONエンコード整形",
    "JSONデコード",
    "JSON_E",
    "JSON_ES",
    "JSON_D",
    "正規表現マッチ",
    "正規表現抽出",
    "抽出文字列",
    "正規表現置換",
    "正規表現区切",
    "辞書キー列挙",
    "辞書キー削除",
    "辞書キー存在",
    "ハッシュキー列挙",
    "ハッシュ内容列挙",
    "ハッシュキー削除",
    "ハッシュキー存在",
    "表示",
    "継続表示",
    "連続表示",
    "連続無改行表示",
    "表示ログ",
    "表示ログクリア",
    "言",
    "コンソール表示",
    "秒待",
    "秒待機",
    "秒逐次待機",
    "秒後",
    "秒毎",
    "秒タイマー開始時",
    "タイマー停止",
    "全タイマー停止",
    "SIN",
    "COS",
    "TAN",
    "ARCSIN",
    "ARCCOS",
    "ARCTAN",
    "ATAN2",
    "座標角度計算",
    "RAD2DEG",
    "DEG2RAD",
    "度変換",
    "ラジアン変換",
    "SIGN",
    "符号",
    "ABS",
    "絶対値",
    "EXP",
    "HYPOT",
    "斜辺",
    "LN",
    "LOG",
    "LOGN",
    "FRAC",
    "小数部分",
    "整数部分",
    "乱数",
    "乱数範囲",
    "SQRT",
    "平方根",
    "ROUND",
    "四捨五入",
    "小数点切上",
    "小数点切下",
    "小数点四捨五入",
    "CEIL",
    "切上",
    "FLOOR",
    "切捨",
    "そ",
    "動時",
    "成功時",
    "処理時",
    "失敗時",
    "終了時",
    "束",
    "ASSERT等",
    "テスト実行",
    "テスト等",
    "CSV取得",
    "TSV取得",
    "表CSV変換",
    "CSV変換",
    "表TSV変換",
    "TSV変換",
    "CSVオプション設定",
    "TOML取得",
    "TOML変換",
    "開",
    "読",
    "バイナリ読",
    "保存",
    "SJISファイル読",
    "SJISファイル保存",
    "EUCファイル読",
    "EUCファイル保存",
    "起動待機",
    "コマンド実行",
    "コマンド実行待機",
    "起動",
    "コンソールクリア",
    "起動時",
    "ブラウザ起動",
    "エクスプローラー起動",
    "ファイル列挙",
    "全ファイル列挙",
    "存在",
    "フォルダ存在",
    "フォルダ作成",
    "ファイルコピーデフォルト動作",
    "ファイルコピー",
    "ファイル上書コピー",
    "ファイルコピー時",
    "ファイル移動",
    "ファイル上書移動",
    "ファイル処理時",
    "ファイル処理強制停止",
    "ファイル移動時",
    "ファイル削除",
    "ファイル削除時",
    "ファイル情報取得",
    "ファイルサイズ取得",
    "絶対パス変換",
    "相対パス展開",
    "カレントディレクトリ取得",
    "カレントディレクトリ変更",
    "作業フォルダ取得",
    "作業フォルダ変更",
    "ホームディレクトリ取得",
    "デスクトップ",
    "マイドキュメント",
    "母艦パス",
    "母艦パス取得",
    "テンポラリフォルダ",
    "一時フォルダ作成",
    "環境変数取得",
    "環境変数一覧取得",
    "圧縮解凍ツールパス",
    "圧縮解凍ツールパス変更",
    "解凍",
    "解凍時",
    "圧縮",
    "圧縮時",
    "プロセス終",
    "強制終了時",
    "終了",
    "OS取得",
    "OSアーキテクチャ取得",
    "コマンドライン",
    "ナデシコランタイム",
    "ナデシコランタイムパス",
    "標準入力取得時",
    "尋",
    "文字尋",
    "標準入力全取得",
    "自分IPアドレス取得",
    "自分IPV6アドレス取得",
    "AJAX送信時",
    "AJAX受信時",
    "GET送信時",
    "POST送信時",
    "POSTフォーム送信時",
    "AJAX失敗時",
    "AJAXオプション",
    "AJAXオプション設定",
    "AJAX保障送信",
    "HTTP保障取得",
    "GET保障送信",
    "POST保障送信",
    "POSTフォーム保障送信",
    "AJAX内容取得",
    "AJAX受信",
    "POSTデータ生成",
    "POST送信",
    "POSTフォーム送信",
    "AJAXテキスト取得",
    "AJAX_JSON取得",
    "AJAXバイナリ取得",
    "DISCORD送信",
    "DISCORDファイル送信",
    "LINE送信",
    "LINE画像送信",
    "文字コード変換サポート判定",
    "SJIS変換",
    "SJIS取得",
    "エンコーディング変換",
    "エンコーディング取得",
    "ハッシュ関数一覧取得",
    "ハッシュ値計算",
    "ランダムUUID生成",
    "ランダム配列生成",
    "AJAX:ONERROR",
};
