const std = @import("std");

/// 助詞呼出しの引数スロット定義。standard-cnako.jsonの`args`表記から生成する。
/// スロット`i`の助詞異表記は`josi[slot_starts[i]..next]`（末尾は`josi.len`）で、
/// 空文字列の異表記は助詞なしの末尾値を表す。`is_variable`の最終スロットは
/// 可変長引数で、値が無くても「それ」補完しない。
pub const BuiltinJosi = struct {
    name: []const u8,
    slot_starts: []const usize,
    josi: []const []const u8,
    is_variable: bool,
};

pub const josi_table = [_]BuiltinJosi{
    .{ .name = "真偽判定", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "JS実行", .slot_starts = &.{0}, .josi = &.{ "を", "で" }, .is_variable = false },
    .{ .name = "JSオブジェクト取得", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "JS関数実行", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "で" }, .is_variable = false },
    .{ .name = "AWAIT実行", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "で" }, .is_variable = false },
    .{ .name = "JSメソッド実行", .slot_starts = &.{ 0, 1, 2 }, .josi = &.{ "の", "を", "で" }, .is_variable = false },
    .{ .name = "ナデシコ", .slot_starts = &.{0}, .josi = &.{ "を", "で" }, .is_variable = false },
    .{ .name = "ナデシコ続", .slot_starts = &.{0}, .josi = &.{ "を", "で" }, .is_variable = false },
    .{ .name = "実行", .slot_starts = &.{0}, .josi = &.{ "を", "に", "で" }, .is_variable = false },
    .{ .name = "実行時間計測", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "デバッグ表示", .slot_starts = &.{0}, .josi = &.{ "と", "を", "の" }, .is_variable = false },
    .{ .name = "ハテナ関数設定", .slot_starts = &.{0}, .josi = &.{ "を", "の" }, .is_variable = false },
    .{ .name = "ハテナ関数実行", .slot_starts = &.{0}, .josi = &.{ "の", "を", "と" }, .is_variable = false },
    .{ .name = "エラー発生", .slot_starts = &.{0}, .josi = &.{ "の", "で" }, .is_variable = false },
    .{ .name = "__DEBUG_BP_WAIT", .slot_starts = &.{0}, .josi = &.{"で"}, .is_variable = false },
    .{ .name = "システム関数存在", .slot_starts = &.{0}, .josi = &.{ "が", "の" }, .is_variable = false },
    .{ .name = "プラグイン名設定", .slot_starts = &.{0}, .josi = &.{ "に", "へ" }, .is_variable = false },
    .{ .name = "名前空間設定", .slot_starts = &.{0}, .josi = &.{ "に", "へ" }, .is_variable = false },
    .{ .name = "足", .slot_starts = &.{ 0, 2 }, .josi = &.{ "に", "と", "を" }, .is_variable = false },
    .{ .name = "合計", .slot_starts = &.{0}, .josi = &.{ "と", "を", "の" }, .is_variable = true },
    .{ .name = "引", .slot_starts = &.{ 0, 1 }, .josi = &.{ "から", "を" }, .is_variable = false },
    .{ .name = "掛", .slot_starts = &.{ 0, 2 }, .josi = &.{ "に", "と", "を" }, .is_variable = false },
    .{ .name = "倍", .slot_starts = &.{ 0, 2 }, .josi = &.{ "の", "を", "" }, .is_variable = false },
    .{ .name = "割", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "で" }, .is_variable = false },
    .{ .name = "割余", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "で" }, .is_variable = false },
    .{ .name = "偶数", .slot_starts = &.{0}, .josi = &.{"が"}, .is_variable = false },
    .{ .name = "奇数", .slot_starts = &.{0}, .josi = &.{"が"}, .is_variable = false },
    .{ .name = "二乗", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "べき乗", .slot_starts = &.{ 0, 1 }, .josi = &.{ "の", "の" }, .is_variable = false },
    .{ .name = "以上", .slot_starts = &.{ 0, 1 }, .josi = &.{ "が", "" }, .is_variable = false },
    .{ .name = "以下", .slot_starts = &.{ 0, 1 }, .josi = &.{ "が", "" }, .is_variable = false },
    .{ .name = "未満", .slot_starts = &.{ 0, 1 }, .josi = &.{ "が", "" }, .is_variable = false },
    .{ .name = "超", .slot_starts = &.{ 0, 1 }, .josi = &.{ "が", "" }, .is_variable = false },
    .{ .name = "等", .slot_starts = &.{ 0, 1 }, .josi = &.{ "が", "と" }, .is_variable = false },
    .{ .name = "等無", .slot_starts = &.{ 0, 1 }, .josi = &.{ "が", "と" }, .is_variable = false },
    .{ .name = "一致", .slot_starts = &.{ 0, 1 }, .josi = &.{ "が", "と" }, .is_variable = false },
    .{ .name = "不一致", .slot_starts = &.{ 0, 1 }, .josi = &.{ "が", "と" }, .is_variable = false },
    .{ .name = "範囲内", .slot_starts = &.{ 0, 1, 2 }, .josi = &.{ "が", "から", "の", "までの" }, .is_variable = false },
    .{ .name = "範囲", .slot_starts = &.{ 0, 1 }, .josi = &.{ "から", "の", "までの" }, .is_variable = false },
    .{ .name = "連続加算", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "に", "と" }, .is_variable = true },
    .{ .name = "MAX", .slot_starts = &.{ 0, 1 }, .josi = &.{ "の", "と" }, .is_variable = true },
    .{ .name = "最大値", .slot_starts = &.{ 0, 1 }, .josi = &.{ "の", "と" }, .is_variable = true },
    .{ .name = "MIN", .slot_starts = &.{ 0, 1 }, .josi = &.{ "の", "と" }, .is_variable = true },
    .{ .name = "最小値", .slot_starts = &.{ 0, 1 }, .josi = &.{ "の", "と" }, .is_variable = true },
    .{ .name = "CLAMP", .slot_starts = &.{ 0, 2, 3 }, .josi = &.{ "の", "を", "から", "までの", "で" }, .is_variable = false },
    .{ .name = "論理OR", .slot_starts = &.{ 0, 1 }, .josi = &.{ "と", "の" }, .is_variable = false },
    .{ .name = "論理AND", .slot_starts = &.{ 0, 1 }, .josi = &.{ "と", "の" }, .is_variable = false },
    .{ .name = "論理NOT", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "OR", .slot_starts = &.{ 0, 1 }, .josi = &.{ "と", "の" }, .is_variable = false },
    .{ .name = "AND", .slot_starts = &.{ 0, 1 }, .josi = &.{ "と", "の" }, .is_variable = false },
    .{ .name = "XOR", .slot_starts = &.{ 0, 1 }, .josi = &.{ "と", "の" }, .is_variable = false },
    .{ .name = "NOT", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "SHIFT_L", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "で" }, .is_variable = false },
    .{ .name = "SHIFT_R", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "で" }, .is_variable = false },
    .{ .name = "SHIFT_UR", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "で" }, .is_variable = false },
    .{ .name = "文字数", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "何文字目", .slot_starts = &.{ 0, 2 }, .josi = &.{ "で", "の", "が" }, .is_variable = false },
    .{ .name = "CHR", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "ASC", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "文字挿入", .slot_starts = &.{ 0, 2, 4 }, .josi = &.{ "で", "の", "に", "へ", "を" }, .is_variable = false },
    .{ .name = "文字検索", .slot_starts = &.{ 0, 2, 3 }, .josi = &.{ "で", "の", "から", "を" }, .is_variable = false },
    .{ .name = "追加", .slot_starts = &.{ 0, 3 }, .josi = &.{ "で", "に", "へ", "を" }, .is_variable = false },
    .{ .name = "一行追加", .slot_starts = &.{ 0, 3 }, .josi = &.{ "で", "に", "へ", "を" }, .is_variable = false },
    .{ .name = "連結", .slot_starts = &.{0}, .josi = &.{ "と", "を" }, .is_variable = true },
    .{ .name = "文字列連結", .slot_starts = &.{0}, .josi = &.{ "と", "を" }, .is_variable = true },
    .{ .name = "文字列分解", .slot_starts = &.{0}, .josi = &.{ "を", "の", "で" }, .is_variable = false },
    .{ .name = "リフレイン", .slot_starts = &.{ 0, 2 }, .josi = &.{ "を", "の", "で" }, .is_variable = false },
    .{ .name = "出現回数", .slot_starts = &.{ 0, 1 }, .josi = &.{ "で", "の" }, .is_variable = false },
    .{ .name = "MID", .slot_starts = &.{ 0, 2, 3 }, .josi = &.{ "で", "の", "から", "を" }, .is_variable = false },
    .{ .name = "文字抜出", .slot_starts = &.{ 0, 2, 3 }, .josi = &.{ "で", "の", "から", "を", "" }, .is_variable = false },
    .{ .name = "LEFT", .slot_starts = &.{ 0, 2 }, .josi = &.{ "の", "で", "だけ" }, .is_variable = false },
    .{ .name = "文字左部分", .slot_starts = &.{ 0, 2 }, .josi = &.{ "の", "で", "だけ", "" }, .is_variable = false },
    .{ .name = "RIGHT", .slot_starts = &.{ 0, 2 }, .josi = &.{ "の", "で", "だけ" }, .is_variable = false },
    .{ .name = "文字右部分", .slot_starts = &.{ 0, 2 }, .josi = &.{ "の", "で", "だけ", "" }, .is_variable = false },
    .{ .name = "区切", .slot_starts = &.{ 0, 2 }, .josi = &.{ "の", "を", "で" }, .is_variable = false },
    .{ .name = "文字列分割", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "で" }, .is_variable = false },
    .{ .name = "切取", .slot_starts = &.{ 0, 2 }, .josi = &.{ "から", "の", "まで", "を" }, .is_variable = false },
    .{ .name = "範囲切取", .slot_starts = &.{ 0, 2, 3 }, .josi = &.{ "で", "の", "から", "まで", "を" }, .is_variable = false },
    .{ .name = "文字削除", .slot_starts = &.{ 0, 1, 2 }, .josi = &.{ "の", "から", "だけ", "を", "" }, .is_variable = false },
    .{ .name = "文字始", .slot_starts = &.{ 0, 1 }, .josi = &.{ "が", "で", "から" }, .is_variable = false },
    .{ .name = "文字終", .slot_starts = &.{ 0, 1 }, .josi = &.{ "が", "で" }, .is_variable = false },
    .{ .name = "出現", .slot_starts = &.{ 0, 2 }, .josi = &.{ "に", "で", "が" }, .is_variable = false },
    .{ .name = "置換", .slot_starts = &.{ 0, 2, 4 }, .josi = &.{ "の", "で", "を", "から", "に", "へ" }, .is_variable = false },
    .{ .name = "単置換", .slot_starts = &.{ 0, 2, 3 }, .josi = &.{ "の", "で", "を", "に", "へ" }, .is_variable = false },
    .{ .name = "トリム", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "空白除去", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "右トリム", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "左トリム", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "末尾空白除去", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "大文字変換", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "小文字変換", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "平仮名変換", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "カタカナ変換", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "英数全角変換", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "英数半角変換", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "英数記号全角変換", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "英数記号半角変換", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "カタカナ全角変換", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "カタカナ半角変換", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "全角変換", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "半角変換", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "通貨形式", .slot_starts = &.{0}, .josi = &.{ "を", "の" }, .is_variable = false },
    .{ .name = "ゼロ埋", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "で" }, .is_variable = false },
    .{ .name = "空白埋", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "で" }, .is_variable = false },
    .{ .name = "かなか判定", .slot_starts = &.{0}, .josi = &.{ "を", "の", "が" }, .is_variable = false },
    .{ .name = "カタカナ判定", .slot_starts = &.{0}, .josi = &.{ "を", "の", "が" }, .is_variable = false },
    .{ .name = "数字判定", .slot_starts = &.{0}, .josi = &.{ "を", "が" }, .is_variable = false },
    .{ .name = "数列判定", .slot_starts = &.{0}, .josi = &.{ "を", "が" }, .is_variable = false },
    .{ .name = "配列結合", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "で" }, .is_variable = false },
    .{ .name = "配列只結合", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "配列検索", .slot_starts = &.{ 0, 2 }, .josi = &.{ "の", "から", "を" }, .is_variable = false },
    .{ .name = "配列要素数", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "要素数", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "LEN", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "配列挿入", .slot_starts = &.{ 0, 1, 3 }, .josi = &.{ "の", "に", "へ", "を" }, .is_variable = false },
    .{ .name = "配列一括挿入", .slot_starts = &.{ 0, 1, 3 }, .josi = &.{ "の", "に", "へ", "を" }, .is_variable = false },
    .{ .name = "配列ソート", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "配列数値変換", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "配列数値ソート", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "配列カスタムソート", .slot_starts = &.{ 0, 1 }, .josi = &.{ "で", "の", "を" }, .is_variable = false },
    .{ .name = "配列逆順", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "配列シャッフル", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "配列削除", .slot_starts = &.{ 0, 2 }, .josi = &.{ "の", "から", "を" }, .is_variable = false },
    .{ .name = "配列切取", .slot_starts = &.{ 0, 2 }, .josi = &.{ "の", "から", "を" }, .is_variable = false },
    .{ .name = "配列取出", .slot_starts = &.{ 0, 1, 2 }, .josi = &.{ "の", "から", "を" }, .is_variable = false },
    .{ .name = "配列ポップ", .slot_starts = &.{0}, .josi = &.{ "の", "から" }, .is_variable = false },
    .{ .name = "配列プッシュ", .slot_starts = &.{ 0, 2 }, .josi = &.{ "に", "へ", "を" }, .is_variable = false },
    .{ .name = "配列追加", .slot_starts = &.{ 0, 2 }, .josi = &.{ "に", "へ", "を" }, .is_variable = false },
    .{ .name = "配列複製", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "配列範囲コピー", .slot_starts = &.{ 0, 2 }, .josi = &.{ "の", "から", "を" }, .is_variable = false },
    .{ .name = "参照", .slot_starts = &.{ 0, 2 }, .josi = &.{ "から", "の", "を" }, .is_variable = false },
    .{ .name = "配列参照", .slot_starts = &.{ 0, 2 }, .josi = &.{ "の", "から", "を" }, .is_variable = false },
    .{ .name = "配列足", .slot_starts = &.{ 0, 3 }, .josi = &.{ "に", "へ", "と", "を" }, .is_variable = false },
    .{ .name = "配列最大値", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "配列最小値", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "配列合計", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "配列入替", .slot_starts = &.{ 0, 1, 2 }, .josi = &.{ "の", "と", "を" }, .is_variable = false },
    .{ .name = "配列連番作成", .slot_starts = &.{ 0, 1 }, .josi = &.{ "から", "までの", "まで", "の" }, .is_variable = false },
    .{ .name = "配列要素作成", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "だけ", "で" }, .is_variable = false },
    .{ .name = "配列関数適用", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "へ", "に" }, .is_variable = false },
    .{ .name = "配列マップ", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "へ", "に" }, .is_variable = false },
    .{ .name = "配列フィルタ", .slot_starts = &.{ 0, 2 }, .josi = &.{ "で", "の", "を", "について" }, .is_variable = false },
    .{ .name = "表ソート", .slot_starts = &.{ 0, 1 }, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "表数値ソート", .slot_starts = &.{ 0, 1 }, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "表ピックアップ", .slot_starts = &.{ 0, 1, 2 }, .josi = &.{ "の", "から", "を", "で" }, .is_variable = false },
    .{ .name = "表完全一致ピックアップ", .slot_starts = &.{ 0, 1, 2 }, .josi = &.{ "の", "から", "を", "で" }, .is_variable = false },
    .{ .name = "表検索", .slot_starts = &.{ 0, 1, 3, 4 }, .josi = &.{ "の", "で", "に", "から", "を" }, .is_variable = false },
    .{ .name = "表列数", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "表行数", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "表行列交換", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "表右回転", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "表重複削除", .slot_starts = &.{ 0, 1 }, .josi = &.{ "の", "を", "で" }, .is_variable = false },
    .{ .name = "表列取得", .slot_starts = &.{ 0, 1 }, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "表列挿入", .slot_starts = &.{ 0, 1, 3 }, .josi = &.{ "の", "に", "へ", "を" }, .is_variable = false },
    .{ .name = "表列削除", .slot_starts = &.{ 0, 1 }, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "表列合計", .slot_starts = &.{ 0, 1 }, .josi = &.{ "の", "を", "で" }, .is_variable = false },
    .{ .name = "表曖昧検索", .slot_starts = &.{ 0, 1, 2, 3 }, .josi = &.{ "の", "から", "で", "を" }, .is_variable = false },
    .{ .name = "表正規表現ピックアップ", .slot_starts = &.{ 0, 2, 3 }, .josi = &.{ "の", "で", "から", "を" }, .is_variable = false },
    .{ .name = "曜日", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "曜日番号取得", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "UNIXTIME変換", .slot_starts = &.{0}, .josi = &.{ "の", "を", "から" }, .is_variable = false },
    .{ .name = "UNIX時間変換", .slot_starts = &.{0}, .josi = &.{ "の", "を", "から" }, .is_variable = false },
    .{ .name = "日時変換", .slot_starts = &.{0}, .josi = &.{ "を", "から" }, .is_variable = false },
    .{ .name = "日時書式変換", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "で" }, .is_variable = false },
    .{ .name = "和暦変換", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "年数差", .slot_starts = &.{ 0, 2 }, .josi = &.{ "と", "から", "の", "までの" }, .is_variable = false },
    .{ .name = "月数差", .slot_starts = &.{ 0, 2 }, .josi = &.{ "と", "から", "の", "までの" }, .is_variable = false },
    .{ .name = "日数差", .slot_starts = &.{ 0, 2 }, .josi = &.{ "と", "から", "の", "までの" }, .is_variable = false },
    .{ .name = "時間差", .slot_starts = &.{ 0, 2 }, .josi = &.{ "と", "から", "の", "までの" }, .is_variable = false },
    .{ .name = "分差", .slot_starts = &.{ 0, 2 }, .josi = &.{ "と", "から", "の", "までの" }, .is_variable = false },
    .{ .name = "秒差", .slot_starts = &.{ 0, 2 }, .josi = &.{ "と", "から", "の", "までの" }, .is_variable = false },
    .{ .name = "日時差", .slot_starts = &.{ 0, 2, 4 }, .josi = &.{ "と", "から", "の", "までの", "による" }, .is_variable = false },
    .{ .name = "時間加算", .slot_starts = &.{ 0, 1 }, .josi = &.{ "に", "を" }, .is_variable = false },
    .{ .name = "日付加算", .slot_starts = &.{ 0, 1 }, .josi = &.{ "に", "を" }, .is_variable = false },
    .{ .name = "日時加算", .slot_starts = &.{ 0, 1 }, .josi = &.{ "に", "を" }, .is_variable = false },
    .{ .name = "URLエンコード", .slot_starts = &.{0}, .josi = &.{ "を", "から" }, .is_variable = false },
    .{ .name = "URLデコード", .slot_starts = &.{0}, .josi = &.{ "を", "へ", "に" }, .is_variable = false },
    .{ .name = "URLパラメータ解析", .slot_starts = &.{0}, .josi = &.{ "を", "の", "から" }, .is_variable = false },
    .{ .name = "BASE64エンコード", .slot_starts = &.{0}, .josi = &.{ "を", "から" }, .is_variable = false },
    .{ .name = "BASE64デコード", .slot_starts = &.{0}, .josi = &.{ "を", "へ", "に" }, .is_variable = false },
    .{ .name = "拡張子抽出", .slot_starts = &.{0}, .josi = &.{ "から", "の" }, .is_variable = false },
    .{ .name = "拡張子変更", .slot_starts = &.{ 0, 3 }, .josi = &.{ "の", "を", "から", "に", "へ" }, .is_variable = false },
    .{ .name = "終端パス追加", .slot_starts = &.{0}, .josi = &.{ "に", "へ" }, .is_variable = false },
    .{ .name = "終端パス除去", .slot_starts = &.{0}, .josi = &.{ "の", "から" }, .is_variable = false },
    .{ .name = "終端パス削除", .slot_starts = &.{0}, .josi = &.{ "の", "から" }, .is_variable = false },
    .{ .name = "ファイル名抽出", .slot_starts = &.{0}, .josi = &.{ "の", "から" }, .is_variable = false },
    .{ .name = "パス抽出", .slot_starts = &.{0}, .josi = &.{ "の", "から" }, .is_variable = false },
    .{ .name = "変数型確認", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "TYPEOF", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "文字列変換", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "TOSTR", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "整数変換", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "TOINT", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "実数変換", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "TOFLOAT", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "INT", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "FLOAT", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "NAN判定", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "非数判定", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "HEX", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "進数変換", .slot_starts = &.{ 0, 2 }, .josi = &.{ "を", "の", "" }, .is_variable = false },
    .{ .name = "二進", .slot_starts = &.{0}, .josi = &.{ "を", "の", "から" }, .is_variable = false },
    .{ .name = "二進表示", .slot_starts = &.{0}, .josi = &.{ "を", "の", "から" }, .is_variable = false },
    .{ .name = "RGB", .slot_starts = &.{ 0, 1, 2 }, .josi = &.{ "と", "の", "で" }, .is_variable = false },
    .{ .name = "JSON変換", .slot_starts = &.{0}, .josi = &.{ "を", "の", "から" }, .is_variable = false },
    .{ .name = "JSON取得", .slot_starts = &.{0}, .josi = &.{ "を", "の", "から" }, .is_variable = false },
    .{ .name = "JSONエンコード", .slot_starts = &.{0}, .josi = &.{ "を", "の" }, .is_variable = false },
    .{ .name = "JSONエンコード整形", .slot_starts = &.{0}, .josi = &.{ "を", "の" }, .is_variable = false },
    .{ .name = "JSONデコード", .slot_starts = &.{0}, .josi = &.{ "を", "の", "から" }, .is_variable = false },
    .{ .name = "JSON_E", .slot_starts = &.{0}, .josi = &.{ "を", "の" }, .is_variable = false },
    .{ .name = "JSON_ES", .slot_starts = &.{0}, .josi = &.{ "を", "の" }, .is_variable = false },
    .{ .name = "JSON_D", .slot_starts = &.{0}, .josi = &.{ "を", "の", "から" }, .is_variable = false },
    .{ .name = "正規表現マッチ", .slot_starts = &.{ 0, 2 }, .josi = &.{ "を", "が", "で", "に" }, .is_variable = false },
    .{ .name = "正規表現抽出", .slot_starts = &.{ 0, 2 }, .josi = &.{ "から", "を", "で" }, .is_variable = false },
    .{ .name = "正規表現置換", .slot_starts = &.{ 0, 1, 3 }, .josi = &.{ "の", "を", "から", "で", "に", "へ" }, .is_variable = false },
    .{ .name = "正規表現区切", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "で" }, .is_variable = false },
    .{ .name = "辞書キー列挙", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "辞書キー削除", .slot_starts = &.{ 0, 2 }, .josi = &.{ "から", "の", "を" }, .is_variable = false },
    .{ .name = "辞書キー存在", .slot_starts = &.{ 0, 2 }, .josi = &.{ "の", "に", "が" }, .is_variable = false },
    .{ .name = "ハッシュキー列挙", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "ハッシュ内容列挙", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "ハッシュキー削除", .slot_starts = &.{ 0, 2 }, .josi = &.{ "から", "の", "を" }, .is_variable = false },
    .{ .name = "ハッシュキー存在", .slot_starts = &.{ 0, 2 }, .josi = &.{ "の", "に", "が" }, .is_variable = false },
    .{ .name = "表示", .slot_starts = &.{0}, .josi = &.{ "を", "と" }, .is_variable = false },
    .{ .name = "継続表示", .slot_starts = &.{0}, .josi = &.{ "を", "と" }, .is_variable = false },
    .{ .name = "連続表示", .slot_starts = &.{0}, .josi = &.{ "と", "を" }, .is_variable = true },
    .{ .name = "連続無改行表示", .slot_starts = &.{0}, .josi = &.{ "と", "を" }, .is_variable = true },
    .{ .name = "言", .slot_starts = &.{0}, .josi = &.{ "を", "と" }, .is_variable = false },
    .{ .name = "コンソール表示", .slot_starts = &.{0}, .josi = &.{ "を", "と" }, .is_variable = false },
    .{ .name = "秒待", .slot_starts = &.{0}, .josi = &.{""}, .is_variable = false },
    .{ .name = "秒待機", .slot_starts = &.{0}, .josi = &.{""}, .is_variable = false },
    .{ .name = "秒逐次待機", .slot_starts = &.{0}, .josi = &.{""}, .is_variable = false },
    .{ .name = "秒後", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "" }, .is_variable = false },
    .{ .name = "秒毎", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "" }, .is_variable = false },
    .{ .name = "秒タイマー開始時", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "" }, .is_variable = false },
    .{ .name = "タイマー停止", .slot_starts = &.{0}, .josi = &.{ "の", "で" }, .is_variable = false },
    .{ .name = "CSV取得", .slot_starts = &.{0}, .josi = &.{ "を", "の", "で" }, .is_variable = false },
    .{ .name = "TSV取得", .slot_starts = &.{0}, .josi = &.{ "を", "の", "で" }, .is_variable = false },
    .{ .name = "表CSV変換", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "CSV変換", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "表TSV変換", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "TSV変換", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "CSVオプション設定", .slot_starts = &.{0}, .josi = &.{ "を", "で" }, .is_variable = false },
    .{ .name = "TOML取得", .slot_starts = &.{0}, .josi = &.{ "を", "の", "から" }, .is_variable = false },
    .{ .name = "TOML変換", .slot_starts = &.{0}, .josi = &.{ "を", "から", "の" }, .is_variable = false },
    .{ .name = "SIN", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "COS", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "TAN", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "ARCSIN", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "ARCCOS", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "ARCTAN", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "ATAN2", .slot_starts = &.{ 0, 1 }, .josi = &.{ "と", "の" }, .is_variable = false },
    .{ .name = "座標角度計算", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "RAD2DEG", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "DEG2RAD", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "度変換", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "ラジアン変換", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "SIGN", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "符号", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "ABS", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "絶対値", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "EXP", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "HYPOT", .slot_starts = &.{ 0, 1 }, .josi = &.{ "と", "の" }, .is_variable = false },
    .{ .name = "斜辺", .slot_starts = &.{ 0, 1 }, .josi = &.{ "と", "の" }, .is_variable = false },
    .{ .name = "LN", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "LOG", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "LOGN", .slot_starts = &.{ 0, 1 }, .josi = &.{ "で", "の" }, .is_variable = false },
    .{ .name = "FRAC", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "小数部分", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "整数部分", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "乱数", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "乱数範囲", .slot_starts = &.{ 0, 1 }, .josi = &.{ "から", "までの", "の" }, .is_variable = false },
    .{ .name = "SQRT", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "平方根", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "ROUND", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "四捨五入", .slot_starts = &.{0}, .josi = &.{ "を", "の" }, .is_variable = false },
    .{ .name = "小数点切上", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "で" }, .is_variable = false },
    .{ .name = "小数点切下", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "で" }, .is_variable = false },
    .{ .name = "小数点四捨五入", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "で" }, .is_variable = false },
    .{ .name = "CEIL", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "切上", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "FLOOR", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "切捨", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "動時", .slot_starts = &.{0}, .josi = &.{ "を", "で" }, .is_variable = false },
    .{ .name = "成功時", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "の", "が", "に" }, .is_variable = false },
    .{ .name = "処理時", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "の", "が", "に" }, .is_variable = false },
    .{ .name = "失敗時", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "の", "が", "に" }, .is_variable = false },
    .{ .name = "終了時", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "の", "が", "に" }, .is_variable = false },
    .{ .name = "束", .slot_starts = &.{0}, .josi = &.{ "と", "を" }, .is_variable = true },
    .{ .name = "開", .slot_starts = &.{0}, .josi = &.{ "を", "から" }, .is_variable = false },
    .{ .name = "読", .slot_starts = &.{0}, .josi = &.{ "を", "から" }, .is_variable = false },
    .{ .name = "バイナリ読", .slot_starts = &.{0}, .josi = &.{ "を", "から" }, .is_variable = false },
    .{ .name = "保存", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "へ", "に" }, .is_variable = false },
    .{ .name = "SJISファイル読", .slot_starts = &.{0}, .josi = &.{ "を", "から" }, .is_variable = false },
    .{ .name = "SJISファイル保存", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "へ", "に" }, .is_variable = false },
    .{ .name = "EUCファイル読", .slot_starts = &.{0}, .josi = &.{ "を", "から" }, .is_variable = false },
    .{ .name = "EUCファイル保存", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "へ", "に" }, .is_variable = false },
    .{ .name = "起動待機", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "コマンド実行", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "コマンド実行待機", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "起動", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "起動時", .slot_starts = &.{ 0, 1 }, .josi = &.{ "で", "を" }, .is_variable = false },
    .{ .name = "ブラウザ起動", .slot_starts = &.{0}, .josi = &.{ "を", "で", "の" }, .is_variable = false },
    .{ .name = "エクスプローラー起動", .slot_starts = &.{0}, .josi = &.{ "を", "で", "の" }, .is_variable = false },
    .{ .name = "ファイル列挙", .slot_starts = &.{0}, .josi = &.{ "の", "を", "で" }, .is_variable = false },
    .{ .name = "全ファイル列挙", .slot_starts = &.{0}, .josi = &.{ "の", "を", "で" }, .is_variable = false },
    .{ .name = "存在", .slot_starts = &.{0}, .josi = &.{ "が", "の" }, .is_variable = false },
    .{ .name = "フォルダ存在", .slot_starts = &.{0}, .josi = &.{ "が", "の" }, .is_variable = false },
    .{ .name = "フォルダ作成", .slot_starts = &.{0}, .josi = &.{ "の", "を", "に", "へ" }, .is_variable = false },
    .{ .name = "ファイルコピー", .slot_starts = &.{ 0, 2 }, .josi = &.{ "から", "を", "に", "へ" }, .is_variable = false },
    .{ .name = "ファイル上書コピー", .slot_starts = &.{ 0, 2 }, .josi = &.{ "から", "を", "に", "へ" }, .is_variable = false },
    .{ .name = "ファイルコピー時", .slot_starts = &.{ 0, 1, 3 }, .josi = &.{ "で", "から", "を", "に", "へ" }, .is_variable = false },
    .{ .name = "ファイル移動", .slot_starts = &.{ 0, 2 }, .josi = &.{ "から", "を", "に", "へ" }, .is_variable = false },
    .{ .name = "ファイル上書移動", .slot_starts = &.{ 0, 2 }, .josi = &.{ "から", "を", "に", "へ" }, .is_variable = false },
    .{ .name = "ファイル処理時", .slot_starts = &.{0}, .josi = &.{ "を", "で" }, .is_variable = false },
    .{ .name = "ファイル移動時", .slot_starts = &.{ 0, 1, 3 }, .josi = &.{ "で", "から", "を", "に", "へ" }, .is_variable = false },
    .{ .name = "ファイル削除", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "ファイル削除時", .slot_starts = &.{ 0, 1 }, .josi = &.{ "で", "の", "を" }, .is_variable = false },
    .{ .name = "ファイル情報取得", .slot_starts = &.{0}, .josi = &.{ "の", "から" }, .is_variable = false },
    .{ .name = "ファイルサイズ取得", .slot_starts = &.{0}, .josi = &.{ "の", "から" }, .is_variable = false },
    .{ .name = "絶対パス変換", .slot_starts = &.{0}, .josi = &.{ "を", "の" }, .is_variable = false },
    .{ .name = "相対パス展開", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "で" }, .is_variable = false },
    .{ .name = "カレントディレクトリ変更", .slot_starts = &.{0}, .josi = &.{ "に", "へ" }, .is_variable = false },
    .{ .name = "作業フォルダ変更", .slot_starts = &.{0}, .josi = &.{ "に", "へ" }, .is_variable = false },
    .{ .name = "一時フォルダ作成", .slot_starts = &.{0}, .josi = &.{ "に", "へ" }, .is_variable = false },
    .{ .name = "環境変数取得", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "圧縮解凍ツールパス変更", .slot_starts = &.{0}, .josi = &.{ "に", "へ" }, .is_variable = false },
    .{ .name = "解凍", .slot_starts = &.{ 0, 2 }, .josi = &.{ "を", "から", "に", "へ" }, .is_variable = false },
    .{ .name = "解凍時", .slot_starts = &.{ 0, 1, 3 }, .josi = &.{ "で", "を", "から", "に", "へ" }, .is_variable = false },
    .{ .name = "圧縮", .slot_starts = &.{ 0, 2 }, .josi = &.{ "を", "から", "に", "へ" }, .is_variable = false },
    .{ .name = "圧縮時", .slot_starts = &.{ 0, 1, 3 }, .josi = &.{ "で", "を", "から", "に", "へ" }, .is_variable = false },
    .{ .name = "プロセス終", .slot_starts = &.{0}, .josi = &.{"で"}, .is_variable = false },
    .{ .name = "強制終了時", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "標準入力取得時", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "尋", .slot_starts = &.{0}, .josi = &.{ "と", "を" }, .is_variable = false },
    .{ .name = "文字尋", .slot_starts = &.{0}, .josi = &.{ "と", "を" }, .is_variable = false },
    .{ .name = "ASSERT等", .slot_starts = &.{ 0, 1 }, .josi = &.{ "と", "が" }, .is_variable = false },
    .{ .name = "AJAX送信時", .slot_starts = &.{ 0, 1 }, .josi = &.{ "の", "まで", "へ", "に" }, .is_variable = false },
    .{ .name = "AJAX受信時", .slot_starts = &.{ 0, 1 }, .josi = &.{ "で", "から", "を" }, .is_variable = false },
    .{ .name = "GET送信時", .slot_starts = &.{ 0, 1 }, .josi = &.{ "の", "まで", "へ", "に" }, .is_variable = false },
    .{ .name = "POST送信時", .slot_starts = &.{ 0, 1, 4 }, .josi = &.{ "の", "まで", "へ", "に", "を" }, .is_variable = false },
    .{ .name = "POSTフォーム送信時", .slot_starts = &.{ 0, 1, 4 }, .josi = &.{ "の", "まで", "へ", "に", "を" }, .is_variable = false },
    .{ .name = "AJAX失敗時", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "AJAXオプション設定", .slot_starts = &.{0}, .josi = &.{ "に", "へ", "と" }, .is_variable = false },
    .{ .name = "AJAX保障送信", .slot_starts = &.{0}, .josi = &.{ "まで", "へ", "に" }, .is_variable = false },
    .{ .name = "HTTP保障取得", .slot_starts = &.{0}, .josi = &.{ "の", "から", "を" }, .is_variable = false },
    .{ .name = "GET保障送信", .slot_starts = &.{0}, .josi = &.{ "まで", "へ", "に" }, .is_variable = false },
    .{ .name = "POST保障送信", .slot_starts = &.{ 0, 3 }, .josi = &.{ "まで", "へ", "に", "を" }, .is_variable = false },
    .{ .name = "POSTフォーム保障送信", .slot_starts = &.{ 0, 3 }, .josi = &.{ "まで", "へ", "に", "を" }, .is_variable = false },
    .{ .name = "AJAX内容取得", .slot_starts = &.{ 0, 1 }, .josi = &.{ "から", "で" }, .is_variable = false },
    .{ .name = "AJAX受信", .slot_starts = &.{0}, .josi = &.{ "から", "を" }, .is_variable = false },
    .{ .name = "POSTデータ生成", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "POST送信", .slot_starts = &.{ 0, 3 }, .josi = &.{ "まで", "へ", "に", "を" }, .is_variable = false },
    .{ .name = "POSTフォーム送信", .slot_starts = &.{ 0, 3 }, .josi = &.{ "まで", "へ", "に", "を" }, .is_variable = false },
    .{ .name = "AJAXテキスト取得", .slot_starts = &.{0}, .josi = &.{"から"}, .is_variable = false },
    .{ .name = "AJAX_JSON取得", .slot_starts = &.{0}, .josi = &.{"から"}, .is_variable = false },
    .{ .name = "AJAXバイナリ取得", .slot_starts = &.{0}, .josi = &.{"から"}, .is_variable = false },
    .{ .name = "DISCORD送信", .slot_starts = &.{ 0, 2 }, .josi = &.{ "へ", "に", "を" }, .is_variable = false },
    .{ .name = "DISCORDファイル送信", .slot_starts = &.{ 0, 2, 3 }, .josi = &.{ "へ", "に", "と", "を" }, .is_variable = false },
    .{ .name = "LINE送信", .slot_starts = &.{ 0, 2 }, .josi = &.{ "へ", "に", "を" }, .is_variable = false },
    .{ .name = "LINE画像送信", .slot_starts = &.{ 0, 2, 3 }, .josi = &.{ "へ", "に", "と", "を" }, .is_variable = false },
    .{ .name = "文字コード変換サポート判定", .slot_starts = &.{0}, .josi = &.{ "の", "を" }, .is_variable = false },
    .{ .name = "SJIS変換", .slot_starts = &.{0}, .josi = &.{ "に", "へ", "を" }, .is_variable = false },
    .{ .name = "SJIS取得", .slot_starts = &.{0}, .josi = &.{ "から", "を", "で" }, .is_variable = false },
    .{ .name = "エンコーディング変換", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "へ", "で" }, .is_variable = false },
    .{ .name = "エンコーディング取得", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "から", "で" }, .is_variable = false },
    .{ .name = "ハッシュ値計算", .slot_starts = &.{ 0, 1, 2 }, .josi = &.{ "を", "の", "で" }, .is_variable = false },
    .{ .name = "ランダム配列生成", .slot_starts = &.{0}, .josi = &.{"の"}, .is_variable = false },
    .{ .name = "簡易HTTPサーバ起動時", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "の", "で" }, .is_variable = false },
    .{ .name = "簡易HTTPサーバ静的パス指定", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "に", "へ" }, .is_variable = false },
    .{ .name = "簡易HTTPサーバ受信時", .slot_starts = &.{ 0, 1 }, .josi = &.{ "を", "に", "へ", "で" }, .is_variable = false },
    .{ .name = "簡易HTTPサーバ出力", .slot_starts = &.{0}, .josi = &.{ "を", "と", "の" }, .is_variable = false },
    .{ .name = "簡易HTTPサーバヘッダ出力", .slot_starts = &.{ 0, 1 }, .josi = &.{ "で", "を", "の", "と" }, .is_variable = false },
    .{ .name = "簡易HTTPサーバ移動", .slot_starts = &.{0}, .josi = &.{ "へ", "に" }, .is_variable = false },
    .{ .name = "マークダウンHTML変換", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "HTML整形", .slot_starts = &.{0}, .josi = &.{"を"}, .is_variable = false },
    .{ .name = "漢数字", .slot_starts = &.{0}, .josi = &.{ "を", "の" }, .is_variable = false },
    .{ .name = "算用数字", .slot_starts = &.{0}, .josi = &.{ "を", "の" }, .is_variable = false },
};

pub fn findJosi(name: []const u8) ?BuiltinJosi {
    for (josi_table) |entry| if (std.mem.eql(u8, entry.name, name)) return entry;
    return null;
}
