pub const Kind = enum {
    eof,
    eol,
    comma,
    identifier,
    number,
    bigint,
    string,
    string_template,
    def_func,
    def_test,
    function_ref,
    keyword_if,
    keyword_else,
    keyword_here_from,
    keyword_here_end,
    keyword_repeat_count,
    keyword_repeat_while,
    keyword_repeat,
    keyword_foreach,
    keyword_break,
    keyword_continue,
    keyword_return,
    keyword_let,
    keyword_const,
    keyword_import,
    keyword_error_guard,
    keyword_error,
    keyword_async,
    keyword_mode,
    not,
    logical_and,
    logical_or,
    equal,
    strict_equal,
    not_equal,
    strict_not_equal,
    greater,
    greater_equal,
    less,
    less_equal,
    shift_right_unsigned,
    shift_right,
    shift_left,
    assign_arrow,
    plus,
    minus,
    multiply,
    power,
    divide,
    integer_divide,
    modulo,
    bit_xor,
    bit_and,
    at,
    property,
    question_display,
    range,
    left_paren,
    right_paren,
    left_bracket,
    right_bracket,
    left_brace,
    right_brace,
    pipe,
    colon,
};

pub const Span = struct {
    start: usize,
    end: usize,
    source_start: usize,
    source_end: usize,
    line: usize,
    column: usize,
};

pub const Token = struct {
    kind: Kind,
    lexeme: []const u8,
    value: []const u8,
    number_value: ?f64 = null,
    josi: []const u8 = "",
    raw_josi: []const u8 = "",
    indent: usize = 0,
    span: Span,
};
